import {supabase} from '../lib/supabase';
export type InvestorRow={user_id:string;investor_code:string|null;full_name:string;status:string;units:number;ownership_percent:number;invested_amount:number;created_at:string};
export type OwnershipOfferingRow={id:string;name:string;code:string;status:string;unit_price:number;unit_ownership_percent:number;total_units:number;allocated_units:number;available_units:number};

export type InquiryRow={id:string;name:string;email:string;phone:string|null;organization:string|null;message:string;source_page:string|null;status:string;created_at:string};
export async function listEquityInquiries(){const {data,error}=await client().from('portal_inquiries').select('id,name,email,phone,organization,message,source_page,status,created_at').eq('source_page','equity-interest').order('created_at',{ascending:false});if(error)throw error;return (data||[]) as InquiryRow[]}
export async function setInquiryStatus(id:string,status:'new'|'in_progress'|'closed'){const {error}=await client().schema('app').rpc('set_portal_inquiry_status',{p_inquiry_id:id,p_status:status});if(error)throw error}
export async function convertInquiryToInvestor(inquiry_id:string,investor_id:string){const {error}=await client().schema('app').rpc('convert_portal_inquiry_to_investor',{p_inquiry_id:inquiry_id,p_investor_id:investor_id});if(error)throw error}
export async function findInvestorByEmail(email:string){const normalized=email.trim().toLowerCase();const {data,error}=await client().schema('app').rpc('find_investor_by_email',{p_email:normalized});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)return null;return row as {id:string;reference_code:string;legal_name:string;status:string;email:string}}
export type DistributionRow={id:string;investor_user_id:string;period:string;amount:number;status:string;paid_at:string|null;notes:string|null;created_at:string};
export type FinanceRow={id:string;entry_date:string;type:'income'|'expense';category:string;description:string;amount:number;reference_no:string|null};
export type DocumentRow={id:string;title:string;category:string;file_url:string;audience:string;published:boolean;status:string;created_at:string};
const client=()=>{if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase};
export async function listOwnershipOfferings(){const {data,error}=await client().from('ownership_offerings').select('id,name,code,status,unit_price,unit_ownership_bps,total_units,ownership_holdings(units,status)').eq('status','open').order('created_at',{ascending:false});if(error)throw error;return(data||[]).map((o:any)=>{const allocated=(o.ownership_holdings||[]).filter((h:any)=>['reserved','active'].includes(h.status)).reduce((s:number,h:any)=>s+Number(h.units||0),0);return{id:o.id,name:o.name,code:o.code,status:o.status,unit_price:Number(o.unit_price||0),unit_ownership_percent:Number(o.unit_ownership_bps||0)/100,total_units:Number(o.total_units||0),allocated_units:allocated,available_units:Math.max(0,Number(o.total_units||0)-allocated)}}) as OwnershipOfferingRow[]}
export async function allocateInvestorOwnership(input:{offering_id:string;investor_id:string;units:number;acquisition_reference?:string;notes?:string}){const {error}=await client().schema('app').rpc('allocate_ownership_holding',{p_offering_id:input.offering_id,p_investor_id:input.investor_id,p_units:input.units,p_acquisition_reference:input.acquisition_reference?.trim()||null,p_notes:input.notes?.trim()||null});if(error)throw error}
export async function listInvestors(){const {data,error}=await client().from('investors').select('id,reference_code,legal_name,status,created_at,ownership_holdings(units,ownership_bps,status,ownership_offerings(unit_price))').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const holdings=(r.ownership_holdings||[]).filter((h:any)=>h.status==='active'||h.status==='reserved');const units=holdings.reduce((n:number,h:any)=>n+Number(h.units||0),0);const bps=holdings.reduce((n:number,h:any)=>n+Number(h.ownership_bps||0),0);return {user_id:r.id,investor_code:r.reference_code,full_name:r.legal_name,status:r.status,units,ownership_percent:bps/100,invested_amount:holdings.reduce((n:number,h:any)=>{const o=Array.isArray(h.ownership_offerings)?h.ownership_offerings[0]:h.ownership_offerings;return n+Number(h.units||0)*Number(o?.unit_price||0)},0),created_at:r.created_at}}) as InvestorRow[]}
export async function setInvestorStatus(user_id:string,status:string){const allowed=['prospective','submitted','under_review','approved','rejected','active','inactive'];if(!allowed.includes(status))throw new Error('Status investor tidak valid.');const {error}=await client().rpc('transition_investor',{p_investor_id:user_id,p_to_status:status,p_reason:null});if(error)throw error}
export async function listInvestorDistributions(user_id:string){const {data,error}=await client().from('profit_distribution_allocations').select('id,investor_id,allocation_amount,status,paid_at,payment_reference,created_at,profit_distributions(period_start,period_end,notes)').eq('investor_id',user_id).order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const d=Array.isArray(r.profit_distributions)?r.profit_distributions[0]:r.profit_distributions;return {id:r.id,investor_user_id:r.investor_id,period:d?String(d.period_start)+' — '+String(d.period_end):'—',amount:Number(r.allocation_amount||0),status:r.status,paid_at:r.paid_at,notes:r.payment_reference||d?.notes||null,created_at:r.created_at}}) as DistributionRow[]}
export async function listPayableDistributions(){const {data,error}=await client().from('profit_distribution_allocations').select('id,investor_id,allocation_amount,status,payment_reference,created_at,investors(reference_code,legal_name,bank_name,bank_account_name,bank_account_number),profit_distributions(period_start,period_end)').in('status',['payable','paid']).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function payInvestorDistribution(input:{allocation_id:string;investor_id:string;payment_reference:string;proof?:File}){const ref=input.payment_reference.trim();if(!ref)throw new Error('Referensi pembayaran wajib diisi.');let uploadedPath:string|null=null;if(input.proof){const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const safe=input.proof.name.replace(/[^a-zA-Z0-9._-]/g,'-');uploadedPath=input.investor_id+'/'+input.allocation_id+'/'+Date.now()+'-'+safe;const up=await client().storage.from('profit-distribution-proofs').upload(uploadedPath,input.proof,{contentType:input.proof.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;const ins=await client().from('profit_distribution_payment_proofs').insert({allocation_id:input.allocation_id,investor_id:input.investor_id,storage_bucket:'profit-distribution-proofs',storage_path:uploadedPath,original_file_name:input.proof.name,mime_type:input.proof.type||'application/octet-stream',file_size_bytes:input.proof.size,payment_reference:ref,uploaded_by:user.id});if(ins.error){await client().storage.from('profit-distribution-proofs').remove([uploadedPath]);throw ins.error}}const {error}=await client().schema('app').rpc('mark_profit_distribution_allocation_paid',{p_allocation_id:input.allocation_id,p_payment_reference:ref});if(error)throw error}
export async function listFinance(){const [payments,refunds,expenses]=await Promise.all([client().from('finance_payments').select('id,received_at,created_at,reference,external_reference,amount,notes,status').eq('status','confirmed').order('created_at',{ascending:false}),client().from('finance_refunds').select('id,processed_at,created_at,reference,amount,reason,status').eq('status','processed').order('created_at',{ascending:false}),client().from('finance_expenses').select('id,expense_on,created_at,reference,total_amount,category,description,status').order('created_at',{ascending:false})]);if(payments.error)throw payments.error;if(refunds.error)throw refunds.error;if(expenses.error)throw expenses.error;const rows:FinanceRow[]=[...(payments.data||[]).map((x:any)=>({id:'payment-'+x.id,entry_date:(x.received_at||x.created_at).slice(0,10),type:'income' as const,category:'Pembayaran Invoice',description:x.notes||'Penerimaan pembayaran',amount:Number(x.amount),reference_no:x.external_reference||x.reference||null})),...(refunds.data||[]).map((x:any)=>({id:'refund-'+x.id,entry_date:(x.processed_at||x.created_at).slice(0,10),type:'expense' as const,category:'Refund',description:x.reason||'Refund transaksi',amount:Number(x.amount),reference_no:x.reference||null})),...(expenses.data||[]).filter((x:any)=>x.status!=='void'&&x.status!=='cancelled').map((x:any)=>({id:'expense-'+x.id,entry_date:x.expense_on,type:'expense' as const,category:x.category,description:x.description,amount:Number(x.total_amount),reference_no:x.reference||null}))];return rows.sort((a,b)=>b.entry_date.localeCompare(a.entry_date))}
export async function addFinance(input:Omit<FinanceRow,'id'>){if(input.type!=='expense')throw new Error('Pemasukan berasal otomatis dari pembayaran invoice production.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const {error}=await client().from('finance_expenses').insert({reference:input.reference_no||('EXP-'+crypto.randomUUID().slice(0,8).toUpperCase()),status:'posted',expense_on:input.entry_date,category:input.category,description:input.description,quantity:1,unit_price:input.amount,tax_amount:0,total_amount:input.amount,currency:'IDR',payment_method:'Transfer',recorded_by:user.id});if(error)throw error}
export async function listDocuments(){const {data,error}=await client().from('documents').select('id,title,kind,visibility,status,created_at').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((d:any)=>({id:d.id,title:d.title,category:d.kind,file_url:'',audience:d.visibility,published:d.status==='published',status:d.status,created_at:d.created_at})) as DocumentRow[]}
export async function uploadPortalDocument(input:{file:File;title:string;category:string;audience:'public'|'investor'|'restricted'|'internal';published:boolean}){if(input.file.type!=='application/pdf'&&!input.file.name.toLowerCase().endsWith('.pdf'))throw new Error('Dokumen wajib berformat PDF.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const safe=input.file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${crypto.randomUUID()}-${safe}`;const up=await client().storage.from('company-documents').upload(path,input.file,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const asset=await client().from('media_assets').insert({bucket:'company-documents',path,original_filename:input.file.name,mime_type:'application/pdf',byte_size:input.file.size,visibility:'private',uploaded_by:user.id,finalized_at:new Date().toISOString()}).select('id').single();if(asset.error){await client().storage.from('company-documents').remove([path]);throw asset.error}const kind=['investment_proposal','pitch_deck','investor_report','business_update','supporting'].includes(input.category)?input.category:'supporting';const visibility=input.audience==='investor'?'investors':input.audience;const slug=(input.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'dokumen')+'-'+crypto.randomUUID().slice(0,8);const created=await client().schema('app').rpc('create_document_with_draft',{p_title:input.title,p_slug:slug,p_kind:kind,p_summary:null,p_visibility:visibility,p_file_asset_id:asset.data.id});if(created.error){await client().from('media_assets').delete().eq('id',asset.data.id);await client().storage.from('company-documents').remove([path]);throw created.error}if(input.published){const id=typeof created.data==='string'?created.data:(Array.isArray(created.data)?created.data[0]?.id:created.data?.id);if(id){for(const target of ['review','approved','published']){const t=await client().schema('app').rpc('transition_document_publication',{p_document_id:id,p_target:target});if(t.error)throw t.error}}}}
export async function transitionDocument(id:string,target:'review'|'approved'|'published'|'archived'){const {error}=await client().schema('app').rpc('transition_document_publication',{p_document_id:id,p_target:target});if(error)throw error}
export async function setDocumentPublished(id:string,published:boolean){return transitionDocument(id,published?'published':'archived')}
export async function grantDocumentToInvestor(document_id:string,investor_id:string,note?:string){const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const {error}=await client().from('document_access_grants').insert({document_id,investor_id,granted_by:user.id,note:note||null});if(error)throw error}
export async function listDocumentGrants(document_id:string){const {data,error}=await client().from('document_access_grants').select('id,investor_id,granted_at,revoked_at,note,investors(reference_code,legal_name)').eq('document_id',document_id).order('granted_at',{ascending:false});if(error)throw error;return data||[]}
export async function revokeDocumentGrant(id:string){const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const {error}=await client().from('document_access_grants').update({revoked_at:new Date().toISOString(),revoked_by:user.id}).eq('id',id).is('revoked_at',null);if(error)throw error}
export async function deletePortalDocument(_id:string,_file_url:string){throw new Error('Dokumen canonical menggunakan versioning. Gunakan arsip agar audit trail tetap terjaga.')}

export type SalesInvoice={id:string;invoice_no:string;customer_name:string;customer_email?:string|null;customer_phone?:string|null;product_type:string;product_name:string;product_code:string|null;pax:number;departure_date:string|null;due_date:string|null;subtotal:number;total_amount:number;paid_amount:number;refunded_amount:number;payment_status:string;transaction_status:string;created_at:string};
export type SalesPayment={id:string;invoice_id:string;payment_date:string;amount:number;kind:'payment'|'refund';method:string;reference_no:string|null;notes:string|null;status:string;created_at:string};
const financeRpc=()=>client().schema('app');
export async function listSalesInvoices(){const {data,error}=await client().from('finance_invoices').select('*,finance_invoice_items(name,product_code_snapshot,quantity,unit_label)').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const item=r.finance_invoice_items?.[0]||{};return {id:r.id,invoice_no:r.reference,customer_name:r.customer_name,customer_email:r.customer_email,customer_phone:r.customer_phone,product_type:item.unit_label||'package',product_name:item.name||'Paket',product_code:item.product_code_snapshot||null,pax:Number(item.quantity||1),departure_date:r.departure_on,due_date:r.due_on,subtotal:Number(r.subtotal||0),total_amount:Number(r.grand_total||0),paid_amount:Number(r.paid_total||0),refunded_amount:Number(r.refunded_total||0),payment_status:r.status,transaction_status:r.status,created_at:r.created_at}}) as SalesInvoice[]}
export async function createSalesInvoice(input:{customer_name:string;customer_email?:string;customer_phone?:string;product_type:string;product_name:string;product_code?:string;pax:number;departure_date?:string;due_date?:string;total_amount:number}){const unitPrice=input.pax>0?input.total_amount/input.pax:input.total_amount;const {data,error}=await financeRpc().rpc('create_finance_invoice',{p_customer_name:input.customer_name,p_customer_email:input.customer_email||null,p_customer_phone:input.customer_phone||null,p_customer_address:null,p_due_on:input.due_date||null,p_notes:input.product_type,p_items:[{name:input.product_name,product_code:input.product_code||null,description:input.product_type,quantity:input.pax,unit_label:'pax',unit_price:unitPrice,discount_amount:0,tax_rate:0}]});if(error)throw error;const id=String(data);if(input.departure_date){const d=await financeRpc().rpc('set_finance_invoice_departure',{p_invoice_id:id,p_departure_on:input.departure_date});if(d.error)throw d.error}const issued=await financeRpc().rpc('issue_finance_invoice',{p_invoice_id:id});if(issued.error)throw issued.error;return (await listSalesInvoices()).find(x=>x.id===id)!}
export async function postSalesPayment(input:{invoice_id:string;amount:number;kind:'payment'|'refund';method:string;reference_no?:string;notes?:string;payment_id?:string}){if(input.kind==='payment'){const {error}=await financeRpc().rpc('record_finance_payment',{p_invoice_id:input.invoice_id,p_amount:input.amount,p_method:input.method,p_received_at:new Date().toISOString(),p_external_reference:input.reference_no||null,p_notes:input.notes||null,p_idempotency_key:crypto.randomUUID()});if(error)throw error;return}const payments=await listSalesPayments(input.invoice_id);const confirmed=payments.filter(p=>p.kind==='payment'&&p.status==='confirmed');const payment=input.payment_id?confirmed.find(p=>p.id===input.payment_id):confirmed.length===1?confirmed[0]:null;if(!payment)throw new Error(confirmed.length>1?'Pilih pembayaran terkonfirmasi yang akan direfund.':'Refund memerlukan pembayaran terkonfirmasi.');const {error}=await financeRpc().rpc('process_finance_refund',{p_invoice_id:input.invoice_id,p_payment_id:payment.id,p_amount:input.amount,p_reason:input.notes||'Refund transaksi',p_notes:input.reference_no||null});if(error)throw error}
export async function reconcileSalesPayment(input:{payment_id:string;invoice_id:string;bank_reference:string;bank_amount:number;bank_received_at?:string;notes?:string;proof:File}){if(!input.proof)throw new Error('Bukti pembayaran wajib diunggah.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const safe=input.proof.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path='finance/'+input.invoice_id+'/'+input.payment_id+'/'+Date.now()+'-'+safe;const up=await client().storage.from('company-documents').upload(path,input.proof,{contentType:input.proof.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;const asset=await client().from('media_assets').insert({bucket:'company-documents',path,original_filename:input.proof.name,mime_type:input.proof.type||'application/octet-stream',byte_size:input.proof.size,visibility:'private',uploaded_by:user.id,finalized_at:new Date().toISOString()}).select('id').single();if(asset.error){await client().storage.from('company-documents').remove([path]);throw asset.error}const {error}=await financeRpc().rpc('reconcile_finance_payment',{p_payment_id:input.payment_id,p_proof_asset_id:asset.data.id,p_bank_reference:input.bank_reference.trim(),p_bank_amount:input.bank_amount,p_bank_received_at:input.bank_received_at||new Date().toISOString(),p_notes:input.notes||null});if(error)throw error}
export async function listSalesPayments(invoice_id:string){const [p,r]=await Promise.all([client().from('finance_payments').select('*').eq('invoice_id',invoice_id).order('created_at',{ascending:true}),client().from('finance_refunds').select('*').eq('invoice_id',invoice_id).order('created_at',{ascending:true})]);if(p.error)throw p.error;if(r.error)throw r.error;return [...(p.data||[]).map((x:any)=>({id:x.id,invoice_id:x.invoice_id,payment_date:x.received_at||x.created_at,amount:Number(x.amount),kind:'payment' as const,method:x.method,reference_no:x.external_reference||x.reference,notes:x.notes,status:x.status,created_at:x.created_at})),...(r.data||[]).map((x:any)=>({id:x.id,invoice_id:x.invoice_id,payment_date:x.processed_at||x.created_at,amount:Number(x.amount),kind:'refund' as const,method:'Refund',reference_no:x.reference,notes:x.reason||x.notes,status:x.status,created_at:x.created_at}))] as SalesPayment[]}
export type SalesInvoiceEvent={id:string;invoice_id:string;event_type:string;from_status:string|null;to_status:string|null;amount:number|null;reference_no:string|null;notes:string|null;created_at:string};
export async function listSalesInvoiceEvents(invoice_id:string){const rows=await listSalesPayments(invoice_id);return rows.map(x=>({id:x.id,invoice_id:x.invoice_id,event_type:x.kind==='refund'?'refund':'payment',from_status:null,to_status:null,amount:x.amount,reference_no:x.reference_no,notes:x.notes,created_at:x.created_at}))}
export async function voidSalesInvoice(_invoice_id:string,_reason:string){throw new Error('Pembatalan invoice production harus melalui workflow finance yang diaudit.')}


export type FinancialPeriodRow={id:string;period_type:string;fiscal_year:number;period_index:number;starts_on:string;ends_on:string;currency:string;status:string};
export async function listFinancialPeriods(){const {data,error}=await client().from('financial_periods').select('id,period_type,fiscal_year,period_index,starts_on,ends_on,currency,status').order('starts_on',{ascending:false});if(error)throw error;return (data||[]) as FinancialPeriodRow[]}
export async function createMonthlyFinancialPeriod(year:number,month:number){const {data,error}=await client().schema('app').rpc('create_monthly_financial_period',{p_year:year,p_month:month});if(error)throw error;return data as FinancialPeriodRow}
export async function closeFinancialPeriod(id:string){const {data,error}=await client().from('financial_periods').update({status:'closed'}).eq('id',id).select('id,period_type,fiscal_year,period_index,starts_on,ends_on,currency,status').single();if(error)throw error;return data as FinancialPeriodRow}
