import {supabase} from '../lib/supabase';import type {AdminModule} from './adminAccess';
export interface AdminRole{id:string;key:string;name:string}
export interface AdminRow{user_id:string;full_name:string;email:string;role:string;role_id:string;role_key:string;title:string|null;is_active:boolean;permissions:AdminModule[];created_at:string}
const db=()=>{if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase};
const moduleMap:(readonly [AdminModule,string[]])[]=[['portal',['portal.view']],['investor',['investors.view']],['kasir',['finance_invoices.create','finance_invoices.issue','finance_invoices.update_draft','finance_invoices.void','finance_payments.create','finance_payments.reconcile','finance_payments.fail','finance_refunds.request','finance_refunds.approve','finance_refunds.process']],['keuangan',['finance_expenses.record','finance_expenses.void','financial_periods.view','financial_reports.view','profit_distributions.view','profit_distribution_payments.view']],['laporan',['financial_reports.view','audit_logs.view']],['dokumen',['documents.view']],['admin',['admins.view','roles.view']],['pengaturan',['settings.view']]];
export async function listAdminRoles(){const {data,error}=await db().from('roles').select('id,key,name').order('name');if(error)throw error;return (data||[]) as AdminRole[]}
export async function listAdmins(){const {data,error}=await db().from('admins').select('id,role_id,title,is_active,created_at,user_accounts(full_name,email),roles(key,name,role_permissions(permissions(key)))').order('created_at');if(error)throw error;return (data||[]).map((a:any)=>{const u=Array.isArray(a.user_accounts)?a.user_accounts[0]:a.user_accounts;const role=Array.isArray(a.roles)?a.roles[0]:a.roles;const keys=(role?.role_permissions||[]).map((rp:any)=>rp.permissions?.key).filter(Boolean);const modules:AdminModule[]=['ringkasan',...moduleMap.filter(([,required])=>role?.key==='super_admin'||required.some(k=>keys.includes(k))).map(([m])=>m)];return {user_id:a.id,full_name:u?.full_name||'Admin',email:u?.email||'',role:role?.name||a.title||'Admin',role_id:a.role_id,role_key:role?.key||'',title:a.title,is_active:a.is_active,permissions:[...new Set(modules)],created_at:a.created_at}}) as AdminRow[]}
async function updateAdminCanonical(user_id:string,input:{full_name?:string;role_key:string;title?:string;is_active:boolean}){const {data,error}=await db().functions.invoke('admin-provisioning',{body:{action:'update_admin',admin_id:user_id,...input}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function updateAdminAccess(user_id:string,input:{full_name:string;role_key:string;title:string;is_active:boolean}){return updateAdminCanonical(user_id,input)}
export async function removeAdmin(user_id:string,input:{full_name:string;role_key:string;title:string}){return updateAdminCanonical(user_id,{...input,is_active:false})}
export async function activateAdmin(user_id:string,input:{full_name:string;role_key:string;title:string}){return updateAdminCanonical(user_id,{...input,is_active:true})}

export async function createAdmin(input:{email:string;full_name:string;role_key:string;title?:string;phone?:string}){const {data,error}=await db().functions.invoke('admin-provisioning',{body:{action:'create_admin',...input}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function createInvestor(input:{email:string;legal_name:string;investor_type:'individual'|'institution';whatsapp_number?:string;country?:string;city?:string;address?:string;organization_name?:string;organization_role?:string;application_note?:string}){const email=input.email.trim().toLowerCase();const {data,error}=await db().functions.invoke('admin-provisioning',{body:{action:'create_investor',...input,email}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
