import {supabase} from '../lib/supabase';import type {AdminModule} from './adminAccess';
export interface AdminRole{id:string;key:string;name:string}
export interface AdminRow{user_id:string;full_name:string;email:string;role:string;role_id:string;role_key:string;title:string|null;is_active:boolean;permissions:AdminModule[];created_at:string}
const db=()=>{if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase};
const moduleMap:(readonly [AdminModule,string[]])[]=[['portal',['portal.view']],['investor',['investors.view']],['kasir',['financial_reports.create','financial_reports.update']],['keuangan',['financial_periods.view','financial_reports.view','profit_distributions.view']],['laporan',['financial_reports.view','audit_logs.view']],['dokumen',['documents.view']],['admin',['admins.view','roles.view']],['pengaturan',['settings.view']]];
export async function listAdminRoles(){const {data,error}=await db().from('roles').select('id,key,name').order('name');if(error)throw error;return (data||[]) as AdminRole[]}
export async function listAdmins(){const {data,error}=await db().from('admins').select('id,role_id,title,is_active,created_at,user_accounts(full_name,email),roles(key,name,role_permissions(permissions(key)))').order('created_at');if(error)throw error;return (data||[]).map((a:any)=>{const u=Array.isArray(a.user_accounts)?a.user_accounts[0]:a.user_accounts;const role=Array.isArray(a.roles)?a.roles[0]:a.roles;const keys=(role?.role_permissions||[]).map((rp:any)=>rp.permissions?.key).filter(Boolean);const modules:AdminModule[]=['ringkasan',...moduleMap.filter(([,required])=>role?.key==='super_admin'||required.some(k=>keys.includes(k))).map(([m])=>m)];return {user_id:a.id,full_name:u?.full_name||'Admin',email:u?.email||'',role:role?.name||a.title||'Admin',role_id:a.role_id,role_key:role?.key||'',title:a.title,is_active:a.is_active,permissions:[...new Set(modules)],created_at:a.created_at}}) as AdminRow[]}
export async function updateAdminAccess(user_id:string,input:{full_name:string;role_id:string;title:string}){const {error}=await db().rpc('update_admin_account',{p_admin_id:user_id,p_full_name:input.full_name,p_role_id:input.role_id,p_title:input.title});if(error)throw error}
export async function removeAdmin(user_id:string){const {error}=await db().rpc('deactivate_admin_account',{p_admin_id:user_id,p_reason:'Akses dinonaktifkan dari Dashboard Admin'});if(error)throw error}
export async function activateAdmin(user_id:string){const {error}=await db().rpc('activate_admin_account',{p_admin_id:user_id});if(error)throw error}
