import {supabase} from '../lib/supabase';
export type InvestorRow={user_id:string;investor_code:string|null;full_name:string;status:string;units:number;ownership_percent:number;invested_amount:number;created_at:string};
export type DistributionRow={id:string;investor_user_id:string;period:string;amount:number;status:string;paid_at:string|null;notes:string|null;created_at:string};
export type CashRow={id:string;transaction_date:string;reference_no:string;description:string;amount:number;payment_method:string;status:string;investor_user_id?:string|null;category?:string};
export type FinanceRow={id:string;entry_date:string;type:'income'|'expense';category:string;description:string;amount:number;reference_no:string|null};
export type DocumentRow={id:string;title:string;category:string;file_url:string;audience:string;published:boolean;created_at:string};
const client=()=>{if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase};
export async function listInvestors(){const {data,error}=await client().from('investors').select('id,reference_code,legal_name,status,created_at,ownership_holdings(units,ownership_bps,status)').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const holdings=(r.ownership_holdings||[]).filter((h:any)=>h.status==='active'||h.status==='reserved');const units=holdings.reduce((n:number,h:any)=>n+Number(h.units||0),0);const bps=holdings.reduce((n:number,h:any)=>n+Number(h.ownership_bps||0),0);return {user_id:r.id,investor_code:r.reference_code,full_name:r.legal_name,status:r.status,units,ownership_percent:bps/100,invested_amount:units*100000000,created_at:r.created_at}}) as InvestorRow[]}
export async function setInvestorStatus(user_id:string,status:string){const allowed=['prospective','submitted','under_review','approved','rejected','active','inactive'];if(!allowed.includes(status))throw new Error('Status investor tidak valid.');const {error}=await client().rpc('transition_investor',{p_investor_id:user_id,p_to_status:status,p_reason:null});if(error)throw error}
export async function listCash(){const {data,error}=await client().from('cash_transactions').select('*').order('transaction_date',{ascending:false});if(error)throw error;return data as CashRow[]}
export async function addCash(input:Omit<CashRow,'id'>){const {error}=await client().rpc('post_cash_transaction',{p_transaction_date:input.transaction_date,p_reference_no:input.reference_no,p_description:input.description,p_amount:input.amount,p_payment_method:input.payment_method,p_investor_user_id:input.investor_user_id||null,p_category:input.category||'Penerimaan Investor'});if(error)throw error}
export async function listFinance(){const [payments,refunds,expenses]=await Promise.all([client().from('finance_payments').select('id,received_at,created_at,reference,external_reference,amount,notes,status').eq('status','confirmed').order('created_at',{ascending:false}),client().from('finance_refunds').select('id,processed_at,created_at,reference,amount,reason,status').eq('status','processed').order('created_at',{ascending:false}),client().from('finance_expenses').select('id,expense_on,created_at,reference,total_amount,category,description,status').order('created_at',{ascending:false})]);if(payments.error)throw payments.error;if(refunds.error)throw refunds.error;if(expenses.error)throw expenses.error;const rows:FinanceRow[]=[...(payments.data||[]).map((x:any)=>({id:'payment-'+x.id,entry_date:(x.received_at||x.created_at).slice(0,10),type:'income' as const,category:'Pembayaran Invoice',description:x.notes||'Penerimaan pembayaran',amount:Number(x.amount),reference_no:x.external_reference||x.reference||null})),...(refunds.data||[]).map((x:any)=>({id:'refund-'+x.id,entry_date:(x.processed_at||x.created_at).slice(0,10),type:'expense' as const,category:'Refund',description:x.reason||'Refund transaksi',amount:Number(x.amount),reference_no:x.reference||null})),...(expenses.data||[]).filter((x:any)=>x.status!=='void'&&x.status!=='cancelled').map((x:any)=>({id:'expense-'+x.id,entry_date:x.expense_on,type:'expense' as const,category:x.category,description:x.description,amount:Number(x.total_amount),reference_no:x.reference||null}))];return rows.sort((a,b)=>b.entry_date.localeCompare(a.entry_date))}
export async function addFinance(input:Omit<FinanceRow,'id'>){if(input.type!=='expense')throw new Error('Pemasukan berasal otomatis dari pembayaran invoice production.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const {error}=await client().from('finance_expenses').insert({reference:input.reference_no||('EXP-'+crypto.randomUUID().slice(0,8).toUpperCase()),status:'posted',expense_on:input.entry_date,category:input.category,description:input.description,quantity:1,unit_price:input.amount,tax_amount:0,total_amount:input.amount,currency:'IDR',payment_method:'Transfer',recorded_by:user.id});if(error)throw error}
export async function listDocuments(){const {data,error}=await client().from('portal_documents').select('*').order('created_at',{ascending:false});if(error)throw error;return data as DocumentRow[]}

export async function updateInvestorPortfolio(_user_id:string,_input:{investor_code:string;units:number;ownership_percent:number;invested_amount:number}){throw new Error('Kepemilikan investor dikelola melalui ownership_holdings dan tidak dapat diubah langsung dari profil.')}
export async function listInvestorDistributions(user_id:string){const {data,error}=await client().from('profit_distribution_allocations').select('id,investor_id,allocation_amount,status,paid_at,payment_reference,created_at,profit_distributions(period_start,period_end,notes)').eq('investor_id',user_id).order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const d=Array.isArray(r.profit_distributions)?r.profit_distributions[0]:r.profit_distributions;return {id:r.id,investor_user_id:r.investor_id,period:d?String(d.period_start)+' — '+String(d.period_end):'—',amount:Number(r.allocation_amount||0),status:r.status,paid_at:r.paid_at,notes:r.payment_reference||d?.notes||null,created_at:r.created_at}}) as DistributionRow[]}
export async function addInvestorDistribution(_input:{investor_user_id:string;period:string;amount:number;notes?:string}){throw new Error('Distribusi investor dibuat dari laporan keuangan dan ownership snapshot, bukan nominal manual per investor.')}
export async function listPayableDistributions(){const {data,error}=await client().from('profit_distribution_allocations').select('id,investor_id,allocation_amount,status,payment_reference,created_at,investors(reference_code,legal_name,bank_name,bank_account_name,bank_account_number),profit_distributions(period_start,period_end)').in('status',['payable','paid']).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function payInvestorDistribution(input:{allocation_id:string;investor_id:string;payment_reference:string;proof?:File}){const ref=input.payment_reference.trim();if(!ref)throw new Error('Referensi pembayaran wajib diisi.');let uploadedPath:string|null=null;if(input.proof){const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const safe=input.proof.name.replace(/[^a-zA-Z0-9._-]/g,'-');uploadedPath=input.investor_id+'/'+input.allocation_id+'/'+Date.now()+'-'+safe;const up=await client().storage.from('profit-distribution-proofs').upload(uploadedPath,input.proof,{contentType:input.proof.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;const ins=await client().from('profit_distribution_payment_proofs').insert({allocation_id:input.allocation_id,investor_id:input.investor_id,storage_bucket:'profit-distribution-proofs',storage_path:uploadedPath,original_file_name:input.proof.name,mime_type:input.proof.type||'application/octet-stream',file_size_bytes:input.proof.size,payment_reference:ref,uploaded_by:user.id});if(ins.error){await client().storage.from('profit-distribution-proofs').remove([uploadedPath]);throw ins.error}}const {error}=await client().schema('app').rpc('mark_profit_distribution_allocation_paid',{p_allocation_id:input.allocation_id,p_payment_reference:ref});if(error)throw error}
export async function setDistributionStatus(id:string,status:'pending'|'paid'|'cancelled'){if(status!=='paid')throw new Error('Perubahan status distribusi harus mengikuti workflow production.');const reference='DIST-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+crypto.randomUUID().slice(0,8).toUpperCase();const {error}=await client().schema('app').rpc('mark_profit_distribution_allocation_paid',{p_allocation_id:id,p_payment_reference:reference});if(error)throw error}

export async function uploadPortalDocument(input:{file:File;title:string;category:string;audience:'public'|'investor'|'internal';published:boolean}){const ext=input.file.name.split('.').pop()?.toLowerCase();if(ext!=='pdf')throw new Error('Dokumen wajib berformat PDF.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const safe=input.file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${Date.now()}-${safe}`;const up=await client().storage.from('portal-documents').upload(path,input.file,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const url=client().storage.from('portal-documents').getPublicUrl(path).data.publicUrl;const {error}=await client().from('portal_documents').insert({title:input.title,category:input.category,file_url:url,audience:input.audience,published:input.published,created_by:user.id});if(error){await client().storage.from('portal-documents').remove([path]);throw error}}
export async function setDocumentPublished(id:string,published:boolean){const {error}=await client().from('portal_documents').update({published}).eq('id',id);if(error)throw error}
export async function deletePortalDocument(id:string,file_url:string){const marker='/portal-documents/';const path=file_url.includes(marker)?decodeURIComponent(file_url.split(marker).pop()||''):'';const {error}=await client().from('portal_documents').delete().eq('id',id);if(error)throw error;if(path){const rm=await client().storage.from('portal-documents').remove([path]);if(rm.error)throw rm.error}}

export type SalesInvoice={id:string;invoice_no:string;customer_name:string;customer_email?:string|null;customer_phone?:string|null;product_type:string;product_name:string;product_code:string|null;pax:number;departure_date:string|null;due_date:string|null;subtotal:number;total_amount:number;paid_amount:number;refunded_amount:number;payment_status:string;transaction_status:string;created_at:string};
export type SalesPayment={id:string;invoice_id:string;payment_date:string;amount:number;kind:'payment'|'refund';method:string;reference_no:string|null;notes:string|null;created_at:string};
const financeRpc=()=>client().schema('app');
export async function listSalesInvoices(){const {data,error}=await client().from('finance_invoices').select('*,finance_invoice_items(name,product_code_snapshot,quantity,unit_label)').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const item=r.finance_invoice_items?.[0]||{};return {id:r.id,invoice_no:r.reference,customer_name:r.customer_name,customer_email:r.customer_email,customer_phone:r.customer_phone,product_type:item.unit_label||'package',product_name:item.name||'Paket',product_code:item.product_code_snapshot||null,pax:Number(item.quantity||1),departure_date:r.departure_on,due_date:r.due_on,subtotal:Number(r.subtotal||0),total_amount:Number(r.grand_total||0),paid_amount:Number(r.paid_total||0),refunded_amount:Number(r.refunded_total||0),payment_status:r.status,transaction_status:r.status,created_at:r.created_at}}) as SalesInvoice[]}
export async function createSalesInvoice(input:{customer_name:string;customer_email?:string;customer_phone?:string;product_type:string;product_name:string;product_code?:string;pax:number;departure_date?:string;due_date?:string;total_amount:number}){const unitPrice=input.pax>0?input.total_amount/input.pax:input.total_amount;const {data,error}=await financeRpc().rpc('create_finance_invoice',{p_customer_name:input.customer_name,p_customer_email:input.customer_email||null,p_customer_phone:input.customer_phone||null,p_customer_address:null,p_due_on:input.due_date||null,p_notes:input.product_type,p_items:[{name:input.product_name,product_code:input.product_code||null,description:input.product_type,quantity:input.pax,unit_label:'pax',unit_price:unitPrice,discount_amount:0,tax_rate:0}]});if(error)throw error;const id=String(data);if(input.departure_date){const d=await financeRpc().rpc('set_finance_invoice_departure',{p_invoice_id:id,p_departure_on:input.departure_date});if(d.error)throw d.error}const issued=await financeRpc().rpc('issue_finance_invoice',{p_invoice_id:id});if(issued.error)throw issued.error;return (await listSalesInvoices()).find(x=>x.id===id)!}
export async function postSalesPayment(input:{invoice_id:string;amount:number;kind:'payment'|'refund';method:string;reference_no?:string;notes?:string}){if(input.kind==='payment'){const {error}=await financeRpc().rpc('record_finance_payment',{p_invoice_id:input.invoice_id,p_amount:input.amount,p_method:input.method,p_received_at:new Date().toISOString(),p_external_reference:input.reference_no||null,p_notes:input.notes||null,p_idempotency_key:crypto.randomUUID()});if(error)throw error;return}const payments=await listSalesPayments(input.invoice_id);const payment=payments.find(p=>p.kind==='payment');if(!payment)throw new Error('Refund memerlukan pembayaran terkonfirmasi.');const {error}=await financeRpc().rpc('process_finance_refund',{p_invoice_id:input.invoice_id,p_payment_id:payment.id,p_amount:input.amount,p_reason:input.notes||'Refund transaksi',p_notes:input.reference_no||null});if(error)throw error}
export async function listSalesPayments(invoice_id:string){const [p,r]=await Promise.all([client().from('finance_payments').select('*').eq('invoice_id',invoice_id).order('created_at',{ascending:true}),client().from('finance_refunds').select('*').eq('invoice_id',invoice_id).order('created_at',{ascending:true})]);if(p.error)throw p.error;if(r.error)throw r.error;return [...(p.data||[]).map((x:any)=>({id:x.id,invoice_id:x.invoice_id,payment_date:x.received_at||x.created_at,amount:Number(x.amount),kind:'payment' as const,method:x.method,reference_no:x.external_reference||x.reference,notes:x.notes,created_at:x.created_at})),...(r.data||[]).map((x:any)=>({id:x.id,invoice_id:x.invoice_id,payment_date:x.processed_at||x.created_at,amount:Number(x.amount),kind:'refund' as const,method:'Refund',reference_no:x.reference,notes:x.reason||x.notes,created_at:x.created_at}))] as SalesPayment[]}
export type SalesInvoiceEvent={id:string;invoice_id:string;event_type:string;from_status:string|null;to_status:string|null;amount:number|null;reference_no:string|null;notes:string|null;created_at:string};
export async function listSalesInvoiceEvents(invoice_id:string){const rows=await listSalesPayments(invoice_id);return rows.map(x=>({id:x.id,invoice_id:x.invoice_id,event_type:x.kind==='refund'?'refund':'payment',from_status:null,to_status:null,amount:x.amount,reference_no:x.reference_no,notes:x.notes,created_at:x.created_at}))}
export async function voidSalesInvoice(_invoice_id:string,_reason:string){throw new Error('Pembatalan invoice production harus melalui workflow finance yang diaudit.')}
