import {supabase} from '../lib/supabase';
export type InvestorRow={user_id:string;investor_code:string|null;full_name:string;status:string;units:number;ownership_percent:number;invested_amount:number;created_at:string};
export type DistributionRow={id:string;investor_user_id:string;period:string;amount:number;status:string;paid_at:string|null;notes:string|null;created_at:string};
export type CashRow={id:string;transaction_date:string;reference_no:string;description:string;amount:number;payment_method:string;status:string;investor_user_id?:string|null;category?:string};
export type FinanceRow={id:string;entry_date:string;type:'income'|'expense';category:string;description:string;amount:number;reference_no:string|null};
export type DocumentRow={id:string;title:string;category:string;file_url:string;audience:string;published:boolean;created_at:string};
const client=()=>{if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase};
export async function listInvestors(){const {data,error}=await client().from('investors').select('id,reference_code,legal_name,status,created_at,ownership_holdings(units,ownership_bps,status)').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((r:any)=>{const holdings=(r.ownership_holdings||[]).filter((h:any)=>h.status==='active'||h.status==='reserved');const units=holdings.reduce((n:number,h:any)=>n+Number(h.units||0),0);const bps=holdings.reduce((n:number,h:any)=>n+Number(h.ownership_bps||0),0);return {user_id:r.id,investor_code:r.reference_code,full_name:r.legal_name,status:r.status,units,ownership_percent:bps/100,invested_amount:units*100000000,created_at:r.created_at}}) as InvestorRow[]}
export async function setInvestorStatus(user_id:string,status:string){const allowed=['prospective','submitted','under_review','approved','rejected','active','inactive'];if(!allowed.includes(status))throw new Error('Status investor tidak valid.');const {error}=await client().rpc('transition_investor',{p_investor_id:user_id,p_to_status:status,p_reason:null});if(error)throw error}
export async function listCash(){const {data,error}=await client().from('cash_transactions').select('*').order('transaction_date',{ascending:false});if(error)throw error;return data as CashRow[]}
export async function addCash(input:Omit<CashRow,'id'>){const {error}=await client().rpc('post_cash_transaction',{p_transaction_date:input.transaction_date,p_reference_no:input.reference_no,p_description:input.description,p_amount:input.amount,p_payment_method:input.payment_method,p_investor_user_id:input.investor_user_id||null,p_category:input.category||'Penerimaan Investor'});if(error)throw error}
export async function listFinance(){const [payments,refunds,expenses]=await Promise.all([client().from('finance_payments').select('id,received_at,created_at,reference,external_reference,amount,notes,status').eq('status','confirmed').order('created_at',{ascending:false}),client().from('finance_refunds').select('id,processed_at,created_at,reference,amount,reason,status').eq('status','processed').order('created_at',{ascending:false}),client().from('finance_expenses').select('id,expense_on,created_at,reference,total_amount,category,description,status').order('created_at',{ascending:false})]);if(payments.error)throw payments.error;if(refunds.error)throw refunds.error;if(expenses.error)throw expenses.error;const rows:FinanceRow[]=[...(payments.data||[]).map((x:any)=>({id:'payment-'+x.id,entry_date:(x.received_at||x.created_at).slice(0,10),type:'income' as const,category:'Pembayaran Invoice',description:x.notes||'Penerimaan pembayaran',amount:Number(x.amount),reference_no:x.external_reference||x.reference||null})),...(refunds.data||[]).map((x:any)=>({id:'refund-'+x.id,entry_date:(x.processed_at||x.created_at).slice(0,10),type:'expense' as const,category:'Refund',description:x.reason||'Refund transaksi',amount:Number(x.amount),reference_no:x.reference||null})),...(expenses.data||[]).filter((x:any)=>x.status!=='void'&&x.status!=='cancelled').map((x:any)=>({id:'expense-'+x.id,entry_date:x.expense_on,type:'expense' as const,category:x.category,description:x.description,amount:Number(x.total_amount),reference_no:x.reference||null}))];return rows.sort((a,b)=>b.entry_date.localeCompare(a.entry_date))}
export async function addFinance(input:Omit<FinanceRow,'id'>){if(input.type!=='expense')throw new Error('Pemasukan berasal otomatis dari pembayaran invoice production.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const {error}=await client().from('finance_expenses').insert({reference:input.reference_no||('EXP-'+crypto.randomUUID().slice(0,8).toUpperCase()),status:'posted',expense_on:input.entry_date,category:input.category,description:input.description,quantity:1,unit_price:input.amount,tax_amount:0,total_amount:input.amount,currency:'IDR',payment_method:'Transfer',recorded_by:user.id});if(error)throw error}
export async function listDocuments(){const {data,error}=await client().from('documents').select('id,title,kind,visibility,status,created_at').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((d:any)=>({id:d.id,title:d.title,category:d.kind,file_url:'',audience:d.visibility,published:d.status==='published',created_at:d.created_at})) as DocumentRow[]}
export async function uploadPortalDocument(input:{file:File;title:string;category:string;audience:'public'|'investor'|'internal';published:boolean}){if(input.file.type!=='application/pdf'&&!input.file.name.toLowerCase().endsWith('.pdf'))throw new Error('Dokumen wajib berformat PDF.');const user=(await client().auth.getUser()).data.user;if(!user)throw new Error('Sesi admin tidak tersedia.');const safe=input.file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${crypto.randomUUID()}-${safe}`;const up=await client().storage.from('company-documents').upload(path,input.file,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const asset=await client().from('media_assets').insert({bucket:'company-documents',path,original_filename:input.file.name,mime_type:'application/pdf',byte_size:input.file.size,visibility:'private',uploaded_by:user.id,finalized_at:new Date().toISOString()}).select('id').single();if(asset.error){await client().storage.from('company-documents').remove([path]);throw asset.error}const kind=['investment_proposal','pitch_deck','investor_report','business_update','supporting'].includes(input.category)?input.category:'supporting';const visibility=input.audience==='investor'?'investors':input.audience;const slug=(input.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'dokumen')+'-'+crypto.randomUUID().slice(0,8);const created=await client().schema('app').rpc('create_document_with_draft',{p_title:input.title,p_slug:slug,p_kind:kind,p_summary:null,p_visibility:visibility,p_file_asset_id:asset.data.id});if(created.error){await client().from('media_assets').delete().eq('id',asset.data.id);await client().storage.from('company-documents').remove([path]);throw created.error}if(input.published){const id=typeof created.data==='string'?created.data:(Array.isArray(created.data)?created.data[0]?.id:created.data?.id);if(id){for(const target of ['review','approved','published']){const t=await client().schema('app').rpc('transition_document_publication',{p_document_id:id,p_target:target});if(t.error)throw t.error}}}}
export async function setDocumentPublished(id:string,published:boolean){const target=published?'published':'archived';const {error}=await client().schema('app').rpc('transition_document_publication',{p_document_id:id,p_target:target});if(error)throw error}
export async function deletePortalDocument(_id:string,_file_url:string){throw new Error('Dokumen canonical menggunakan versioning. Gunakan arsip agar audit trail tetap terjaga.')}
