import React,{useEffect,useMemo,useState} from 'react';
import {ChevronRight,Eye,Save,Send} from 'lucide-react';
import {PORTAL_SECTION_DEFINITIONS,type PortalField} from '../../data/portalEditorSchema';
import {StructuredContentEditor} from './StructuredContentEditor';
import {STRUCTURED_TEMPLATES} from '../../data/portalStructuredTemplates';
import {PORTAL_EXISTING_STRUCTURED_DEFAULTS} from '../../data/portalExistingDefaults';
import {PortalDraftPreview} from './PortalDraftPreview';
import {validatePortalDraft} from '../../data/portalValidation';
import {PortalVersionHistory} from './PortalVersionHistory';
import {ensurePortalContentSection,listPortalContent,publishPortalContent,savePortalContent,uploadPortalImage,type PortalCmsSection} from '../../services/portalCms';

const fieldValue=(v:PortalField['value'])=>Array.isArray(v)?v.join('\n'):String(v??'');
export const PortalEditor:React.FC=()=>{
 const [selected,setSelected]=useState(PORTAL_SECTION_DEFINITIONS[0].key);
 const [rows,setRows]=useState<PortalCmsSection[]>([]);
 const [draft,setDraft]=useState<Record<string,string>>({});
 const [message,setMessage]=useState('');const [historyKey,setHistoryKey]=useState('');const [saving,setSaving]=useState(false);const [publishing,setPublishing]=useState(false);const [preview,setPreview]=useState(false);const [uploading,setUploading]=useState('');
 const definition=useMemo(()=>PORTAL_SECTION_DEFINITIONS.find(s=>s.key===selected)!,[selected]);
 const currentRow=useMemo(()=>rows.find(r=>r.key===selected),[rows,selected]);
 const hasDraft=!!currentRow?.draft_content&&JSON.stringify(currentRow.draft_content)!==JSON.stringify(currentRow.content);
 const statusLabel=hasDraft?'Ada Draft':currentRow?.published_at?'Sudah Dipublish':'Belum Dipublish';
 useEffect(()=>{void (async()=>{try{let current=await listPortalContent();for(let i=0;i<PORTAL_SECTION_DEFINITIONS.length;i++){const d=PORTAL_SECTION_DEFINITIONS[i];if(current.some(r=>r.key===d.key))continue;const seed:Object={};for(const field of d.fields)(seed as Record<string,unknown>)[field.key]=PORTAL_EXISTING_STRUCTURED_DEFAULTS[d.key]?.[field.key]??field.value;const created=await ensurePortalContentSection(d.key,d.label,seed as Record<string,unknown>,i+1);current=[...current,created]}setRows(current)}catch(e){setMessage(e instanceof Error?e.message:'CMS belum dapat dimuat.');setRows([])}})()},[]);
 useEffect(()=>{const row=rows.find(r=>r.key===selected);const stored=(row?.draft_content??row?.content) as Record<string,unknown>|undefined;const next:Record<string,string>={};for(const f of definition.fields){const v=stored?.[f.key]??PORTAL_EXISTING_STRUCTURED_DEFAULTS[selected]?.[f.key]??f.value;next[f.key]=f.kind==='json-list'||f.kind==='json-object'?JSON.stringify(v,null,2):Array.isArray(v)?v.join('\n'):String(v??'')}setDraft(next)},[selected,definition,rows]);
 const save=async()=>{const existing=rows.find(r=>r.key===selected);if(!existing){setMessage('Section CMS belum tersedia. Muat ulang dashboard untuk inisialisasi otomatis tanpa mengubah portal publik.');return}setSaving(true);setMessage('');try{const content:Record<string,unknown>={...(existing.draft_content??existing.content??{})};for(const f of definition.fields)content[f.key]=f.kind==='string-list'?draft[f.key].split('\n').map(x=>x.trim()).filter(Boolean):f.kind==='number'?Number(draft[f.key]):f.kind==='json-list'||f.kind==='json-object'?JSON.parse(draft[f.key]||(f.kind==='json-list'?'[]':'{}')):draft[f.key];const next={...existing,content};await savePortalContent(next);setRows(v=>v.map(r=>r.id===next.id?{...r,draft_content:content,draft_updated_at:new Date().toISOString()}:r));setMessage('Draft tersimpan. Portal publik belum berubah.')}catch(e){setMessage(e instanceof Error?e.message:'Gagal menyimpan')}finally{setSaving(false)}};
 const publish=async()=>{const existing=rows.find(r=>r.key===selected);if(!existing)return;const validation=validatePortalDraft(definition.fields,draft);if(!validation.valid){setMessage(`Tidak dapat publish: ${validation.errors.slice(0,4).join(' ')}`);return}setPublishing(true);setMessage('');try{const content:Record<string,unknown>={...(existing.draft_content??existing.content??{})};for(const f of definition.fields)content[f.key]=f.kind==='string-list'?draft[f.key].split('\n').map(x=>x.trim()).filter(Boolean):f.kind==='number'?Number(draft[f.key]):f.kind==='json-list'||f.kind==='json-object'?JSON.parse(draft[f.key]):draft[f.key];await savePortalContent({...existing,content});await publishPortalContent(existing.id);const published=content;setRows(v=>v.map(r=>r.id===existing.id?{...r,content:published,draft_content:published,published_at:new Date().toISOString()}:r));setHistoryKey(String(Date.now()));setMessage('Konten section berhasil dipublish dan versi baru dicatat.')}catch(e){setMessage(e instanceof Error?e.message:'Gagal publish')}finally{setPublishing(false)}};
 return <>{preview&&<PortalDraftPreview title={definition.label} fields={definition.fields} draft={draft} onClose={()=>setPreview(false)}/>}<div className="grid xl:grid-cols-[280px_1fr] gap-5">
  <aside className="bg-white border rounded-2xl p-2 h-fit">{PORTAL_SECTION_DEFINITIONS.map(s=><button key={s.key} onClick={()=>{setSelected(s.key);setMessage('')}} className={`w-full px-3 py-2.5 rounded-xl flex items-center justify-between text-left text-sm ${selected===s.key?'bg-[#131314] text-white':'hover:bg-black/[0.04]'}`}><span className="flex items-center gap-2"><span>{s.label}</span>{(()=>{const r=rows.find(x=>x.key===s.key);const changed=!!r?.draft_content&&JSON.stringify(r.draft_content)!==JSON.stringify(r.content);return changed?<span className="w-2 h-2 rounded-full bg-amber-400"/>:null})()}</span><ChevronRight size={14}/></button>)}</aside>
  <section className="bg-white border rounded-2xl p-5 sm:p-6"><div className="flex flex-wrap gap-4 items-start justify-between border-b pb-5"><div><h2 className="text-xl font-bold">{definition.label}</h2><p className="text-sm text-black/50 mt-1">{definition.description}</p><p className="text-xs text-emerald-700 mt-2 font-medium">Layout dikunci — hanya isi konten yang dapat diedit.</p><div className={`inline-flex mt-3 rounded-full px-2.5 py-1 text-[11px] font-bold ${hasDraft?'bg-amber-100 text-amber-800':currentRow?.published_at?'bg-emerald-100 text-emerald-800':'bg-black/5 text-black/50'}`}>{statusLabel}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setPreview(true)} className="inline-flex items-center gap-2 border border-black/15 bg-white px-4 py-2.5 rounded-xl text-sm font-semibold"><Eye size={15}/>Preview Draft</button><button onClick={save} disabled={saving||publishing||!currentRow||definition.fields.length===0} className="inline-flex items-center gap-2 border border-black/15 bg-white px-4 py-2.5 rounded-xl text-sm font-semibold disabled:opacity-40"><Save size={15}/>{saving?'Menyimpan...':'Simpan Draft'}</button><button onClick={publish} disabled={publishing||saving||!currentRow||definition.fields.length===0} className="inline-flex items-center gap-2 bg-[#131314] text-white px-4 py-2.5 rounded-xl text-sm font-semibold disabled:opacity-40"><Send size={15}/>{publishing?'Publish...':'Publish Section'}</button></div></div>
   {message&&<div className="mt-4 rounded-xl bg-black/[0.04] px-4 py-3 text-sm">{message}</div>}
   {definition.fields.length?<div className="grid md:grid-cols-2 gap-5 pt-6">{definition.fields.map(f=><label key={f.key} className={f.kind==='textarea'||f.kind==='string-list'||f.kind==='json-list'||f.kind==='json-object'?'md:col-span-2':''}><span className="block text-xs font-bold mb-2">{f.label}</span>{(f.kind==='json-list'||f.kind==='json-object')?<StructuredContentEditor value={draft[f.key]??fieldValue(f.value)} objectMode={f.kind==='json-object'} template={STRUCTURED_TEMPLATES[`${selected}.${f.key}`]} onChange={value=>setDraft(v=>({...v,[f.key]:value}))} onUploadImage={async(field,file)=>uploadPortalImage(selected,`${f.key}-${field}`,file)}/>:f.kind==='url'&&(/image|portrait|logo|gambar/i.test(f.key+' '+f.label))?<div className="space-y-2"><input type="url" value={draft[f.key]??fieldValue(f.value)} onChange={e=>setDraft(v=>({...v,[f.key]:e.target.value}))} className="w-full border rounded-xl px-3 py-2.5 text-sm"/><input type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" className="block w-full text-xs" disabled={uploading===f.key} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(f.key);setMessage('');try{const url=await uploadPortalImage(selected,f.key,file);setDraft(v=>({...v,[f.key]:url}));setMessage('Gambar berhasil diupload. Klik Simpan Draft agar perubahan tersimpan tanpa mengubah portal publik.')}catch(err){setMessage(err instanceof Error?err.message:'Upload gambar gagal.')}finally{setUploading('')}}}/>{draft[f.key]&&<img src={draft[f.key]} alt="Preview" className="h-32 w-full object-cover rounded-xl border"/>}</div>:f.kind==='textarea'||f.kind==='string-list'?<textarea value={draft[f.key]??fieldValue(f.value)} onChange={e=>setDraft(v=>({...v,[f.key]:e.target.value}))} rows={f.kind==='string-list'?6:4} className="w-full border rounded-xl px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-black/10"/>:<input type={f.kind==='number'?'number':f.kind==='url'?'url':'text'} value={draft[f.key]??fieldValue(f.value)} onChange={e=>setDraft(v=>({...v,[f.key]:e.target.value}))} className="w-full border rounded-xl px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-black/10"/>}</label>)}</div>:<div className="py-12 text-center"><p className="font-semibold">Editor detail sedang dipetakan dari source portal.</p><p className="text-sm text-black/50 mt-2">Konten portal tidak diubah selama pemetaan ini.</p></div>}
   {currentRow&&<PortalVersionHistory sectionId={currentRow.id} refreshKey={historyKey} onRollback={()=>{setHistoryKey(String(Date.now()));void listPortalContent().then(setRows).catch(()=>setMessage('Muat ulang dashboard untuk melihat hasil rollback.'));setMessage('Rollback berhasil.')}}/>}
  </section>
 </div></>
};
