import React from 'react';
import type {PortalField} from '../../data/portalEditorSchema';

type Props={title:string;fields:PortalField[];draft:Record<string,string>;onClose:()=>void};
const val=(draft:Record<string,string>,f:PortalField)=>draft[f.key]??'';
const parsed=(s:string)=>{try{return JSON.parse(s)}catch{return null}};
export const PortalDraftPreview:React.FC<Props>=({title,fields,draft,onClose})=><div className="fixed inset-0 z-[100] bg-black/60 p-3 sm:p-6 overflow-y-auto">
 <div className="max-w-5xl mx-auto bg-[#F5F5F3] rounded-2xl overflow-hidden shadow-2xl">
  <header className="sticky top-0 z-10 bg-white border-b px-5 py-4 flex items-center justify-between"><div><div className="font-bold">Preview Draft · {title}</div><div className="text-xs text-black/50 mt-1">Preview dashboard saja — portal publik tidak berubah.</div></div><button onClick={onClose} className="border rounded-xl px-3 py-2 text-sm font-semibold">Tutup</button></header>
  <div className="p-5 sm:p-8 space-y-5">{fields.map(f=>{const raw=val(draft,f);if(f.kind==='json-list'){const items=parsed(raw);return <section key={f.key} className="bg-white border rounded-2xl p-5"><div className="text-xs font-bold mb-4">{f.label}</div><div className="grid md:grid-cols-2 gap-3">{Array.isArray(items)&&items.map((item:any,i:number)=><article key={i} className="border rounded-xl p-4">{item.imageUrl&&<img src={item.imageUrl} alt="" className="w-full h-36 object-cover rounded-lg mb-3"/>}{Object.entries(item).filter(([k])=>k!=='imageUrl').map(([k,v])=><div key={k} className="mb-2"><div className="text-[10px] uppercase tracking-wide text-black/40">{k}</div><div className="text-sm whitespace-pre-wrap">{Array.isArray(v)?v.join(' • '):String(v??'')}</div></div>)}</article>)}</div></section>}if(f.kind==='json-object'){const obj=parsed(raw)||{};return <section key={f.key} className="bg-white border rounded-2xl p-5"><div className="text-xs font-bold mb-3">{f.label}</div>{Object.entries(obj).map(([k,v])=><div key={k} className="py-2 border-b last:border-0"><b className="text-xs">{k}</b><div className="text-sm mt-1">{String(v??'')}</div></div>)}</section>}if(f.kind==='url'&&/image|portrait|logo|gambar/i.test(f.key+' '+f.label))return <section key={f.key} className="bg-white border rounded-2xl p-5"><div className="text-xs font-bold mb-3">{f.label}</div>{raw?<img src={raw} alt="" className="max-h-[420px] w-full object-cover rounded-xl"/>:<div className="text-sm text-black/40">Belum ada gambar.</div>}</section>;return <section key={f.key} className="bg-white border rounded-2xl p-5"><div className="text-[11px] font-bold uppercase tracking-wide text-black/40">{f.label}</div><div className={/headline/i.test(f.key)?'text-2xl font-bold mt-2':'text-sm mt-2 whitespace-pre-wrap'}>{f.kind==='string-list'?raw.split('\n').join(' • '):raw}</div></section>})}</div>
 </div>
</div>;
