import React from 'react';
import {Plus,Trash2} from 'lucide-react';

type Props={value:string;objectMode?:boolean;onChange:(value:string)=>void};
const parse=(value:string,objectMode:boolean)=>{try{const x=JSON.parse(value|| (objectMode?'{}':'[]'));return objectMode?(x&&typeof x==='object'&&!Array.isArray(x)?x:{}):(Array.isArray(x)?x:[])}catch{return objectMode?{}:[]}};
export const StructuredContentEditor:React.FC<Props>=({value,objectMode=false,onChange})=>{
 const data=parse(value,objectMode) as Record<string,unknown>|Record<string,unknown>[];
 const commit=(v:unknown)=>onChange(JSON.stringify(v,null,2));
 if(objectMode){const obj=data as Record<string,unknown>;return <div className="space-y-3">{Object.entries(obj).map(([k,v])=><div key={k} className="grid sm:grid-cols-[180px_1fr_auto] gap-2"><input value={k} readOnly className="border rounded-xl px-3 py-2 text-xs bg-black/[0.03]"/><input value={typeof v==='string'?v:JSON.stringify(v)} onChange={e=>commit({...obj,[k]:e.target.value})} className="border rounded-xl px-3 py-2 text-sm"/><button type="button" onClick={()=>{const n={...obj};delete n[k];commit(n)}} className="p-2 text-red-600"><Trash2 size={15}/></button></div>)}<button type="button" onClick={()=>commit({...obj,[`field_${Object.keys(obj).length+1}`]:''})} className="inline-flex gap-2 items-center border rounded-xl px-3 py-2 text-xs font-bold"><Plus size={14}/>Tambah Field</button></div>}
 const items=data as Record<string,unknown>[];return <div className="space-y-3">{items.map((item,i)=><div key={i} className="border rounded-xl p-3 bg-black/[0.015]"><div className="flex justify-between mb-3"><b className="text-xs">Item {i+1}</b><button type="button" onClick={()=>commit(items.filter((_,x)=>x!==i))} className="text-red-600"><Trash2 size={15}/></button></div><div className="grid sm:grid-cols-2 gap-2">{Object.entries(item||{}).map(([k,v])=><label key={k} className="text-xs"><span className="block font-semibold mb-1">{k}</span><input value={typeof v==='string'||typeof v==='number'?String(v):JSON.stringify(v)} onChange={e=>{const n=[...items];n[i]={...item,[k]:e.target.value};commit(n)}} className="w-full border rounded-lg px-2.5 py-2 text-sm bg-white"/></label>)}</div></div>)}<button type="button" onClick={()=>commit([...items,{title:'',description:''}])} className="inline-flex gap-2 items-center border rounded-xl px-3 py-2 text-xs font-bold"><Plus size={14}/>Tambah Item</button></div>
};