import React,{useState} from 'react';
import {Plus,Trash2,Upload} from 'lucide-react';
import type {StructuredTemplate} from '../../data/portalStructuredTemplates';

type Props={value:string;objectMode?:boolean;template?:StructuredTemplate;onChange:(value:string)=>void;onUploadImage?:(field:string,file:File)=>Promise<string>};
const parse=(value:string,objectMode:boolean)=>{try{const x=JSON.parse(value||(objectMode?'{}':'[]'));return objectMode?(x&&typeof x==='object'&&!Array.isArray(x)?x:{}):(Array.isArray(x)?x:[])}catch{return objectMode?{}:[]}};
const display=(v:unknown)=>Array.isArray(v)?v.join('\n'):typeof v==='string'||typeof v==='number'?String(v):JSON.stringify(v??'');
export const StructuredContentEditor:React.FC<Props>=({value,objectMode=false,template,onChange,onUploadImage})=>{
 const [busy,setBusy]=useState('');const data=parse(value,objectMode) as Record<string,unknown>|Record<string,unknown>[];const commit=(v:unknown)=>onChange(JSON.stringify(v,null,2));
 if(objectMode){const obj=data as Record<string,unknown>;return <div className="space-y-3">{Object.entries(obj).map(([k,v])=><div key={k} className="grid sm:grid-cols-[180px_1fr_auto] gap-2"><input value={k} readOnly className="border rounded-xl px-3 py-2 text-xs bg-black/[0.03]"/><input value={display(v)} onChange={e=>commit({...obj,[k]:Array.isArray(v)?e.target.value.split('\n'):typeof v==='number'?Number(e.target.value):typeof v==='boolean'?e.target.value==='true':e.target.value})} className="border rounded-xl px-3 py-2 text-sm"/><button type="button" onClick={()=>{const n={...obj};delete n[k];commit(n)}} className="p-2 text-red-600"><Trash2 size={15}/></button></div>)}<button type="button" onClick={()=>commit({...obj,[`field_${Object.keys(obj).length+1}`]:''})} className="inline-flex gap-2 items-center border rounded-xl px-3 py-2 text-xs font-bold"><Plus size={14}/>Tambah Field</button></div>}
 const items=data as Record<string,unknown>[];const imageFields=template?.imageFields||[];
 return <div className="space-y-3">{items.map((item,i)=><div key={i} className="border rounded-xl p-4 bg-black/[0.015]"><div className="flex justify-between mb-3"><b className="text-xs">{template?.label||'Item'} {i+1}</b><button type="button" onClick={()=>commit(items.filter((_,x)=>x!==i))} className="text-red-600"><Trash2 size={15}/></button></div><div className="grid sm:grid-cols-2 gap-3">{Object.entries(item||{}).map(([k,v])=><label key={k} className={Array.isArray(v)?'sm:col-span-2 text-xs':'text-xs'}><span className="block font-semibold mb-1">{k}</span>{Array.isArray(v)?<textarea rows={3} value={display(v)} onChange={e=>{const n=[...items];n[i]={...item,[k]:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)};commit(n)}} className="w-full border rounded-lg px-2.5 py-2 text-sm bg-white"/>:<><input value={display(v)} onChange={e=>{const n=[...items];n[i]={...item,[k]:typeof v==='number'?Number(e.target.value):e.target.value};commit(n)}} className="w-full border rounded-lg px-2.5 py-2 text-sm bg-white"/>{imageFields.includes(k)&&<div className="mt-2 space-y-2">{Boolean(v)&&<img src={String(v)} alt="" className="h-24 w-full object-cover rounded-lg border"/>}<label className="inline-flex items-center gap-2 border rounded-lg px-2.5 py-2 cursor-pointer font-semibold"><Upload size={13}/>{busy===`${i}:${k}`?'Mengupload...':'Upload Gambar'}<input hidden type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" disabled={!!busy} onChange={async e=>{const file=e.target.files?.[0];if(!file||!onUploadImage)return;const id=`${i}:${k}`;setBusy(id);try{const url=await onUploadImage(k,file);const n=[...items];n[i]={...item,[k]:url};commit(n)}finally{setBusy('')}}}/></label></div>}</>}</label>)}</div></div>)}<button type="button" onClick={()=>commit([...items,{...(template?.fields||{title:'',description:''})}])} className="inline-flex gap-2 items-center border rounded-xl px-3 py-2 text-xs font-bold"><Plus size={14}/>Tambah {template?.label||'Item'}</button></div>
};