import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const allowedOrigins=new Set(["https://www.nuzultrip.click","https://nuzultrip-equity.vercel.app"]);
function cors(req:Request){const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":allowedOrigins.has(o)?o:"https://www.nuzultrip.click","Vary":"Origin","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"}}
Deno.serve(async(req)=>{const ch=cors(req);if(req.method==="OPTIONS")return new Response("ok",{headers:ch});if(req.method!=="POST")return json({error:"Method not allowed"},405,ch);
const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,authHeader=req.headers.get("Authorization")||"";
const caller=createClient(url,anon,{global:{headers:{Authorization:authHeader}}}),admin=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
const requestOrigin=req.headers.get("origin")||"";const portalOrigin=allowedOrigins.has(requestOrigin)?requestOrigin:"https://www.nuzultrip.click";const passwordRedirect=portalOrigin+"/atur-sandi";
const sendPasswordSetup=async(email:string)=>{const {error}=await admin.auth.resetPasswordForEmail(email,{redirectTo:passwordRedirect});return !error};
const allowedAdminRoles=new Set(["admin_document_verification","admin_finance_reporting","admin_internal","admin_investor_relations","admin_portal_communications"]);
const requireSuperAdmin=async()=>{const {data}=await admin.from("admins").select("id,is_active,roles!inner(key),user_accounts!inner(status)").eq("id",actor.id).eq("is_active",true).eq("user_accounts.status","active").maybeSingle();return !!data&&(data as any).roles?.key==="super_admin"};
const {data:userData,error:userError}=await caller.auth.getUser();if(userError||!userData.user)return json({error:"Unauthorized"},401,ch);const actor=userData.user;let body:any;try{body=await req.json()}catch{return json({error:"Invalid JSON"},400,ch)}const action=String(body.action||"");
if(action==="create_admin"){if(!await requireSuperAdmin())return json({error:"Forbidden"},403,ch);const roleKey=String(body.role_key||"");if(!allowedAdminRoles.has(roleKey))return json({error:"Role admin tidak valid."},400,ch);const {data:role}=await admin.from("roles").select("id,key").eq("key",roleKey).neq("key","super_admin").maybeSingle();if(!role)return json({error:"Role tidak ditemukan."},400,ch);const email=String(body.email||"").trim().toLowerCase(),fullName=String(body.full_name||"").trim();if(!email||!fullName)return json({error:"Nama dan email wajib diisi."},400,ch);const {data:created,error:authError}=await admin.auth.admin.createUser({email,email_confirm:true,user_metadata:{full_name:fullName,must_set_password:true}});if(authError||!created.user)return json({error:"Gagal membuat akun admin."},400,ch);const uid=created.user.id;const {error:accountError}=await admin.from("user_accounts").insert({id:uid,account_type:"admin",status:"active",email,full_name:fullName,phone:body.phone||null,locale:"id",timezone:"Asia/Makassar"});if(accountError){await admin.auth.admin.deleteUser(uid);return json({error:"Gagal membuat akun admin."},400,ch)}const {error:adminError}=await admin.from("admins").insert({id:uid,role_id:role.id,title:body.title||null,employee_ref:body.employee_ref||null,is_active:true,created_by:actor.id});if(adminError){await admin.from("user_accounts").delete().eq("id",uid);await admin.auth.admin.deleteUser(uid);return json({error:"Gagal membuat akun admin."},400,ch)}await admin.from("audit_logs").insert({actor_id:actor.id,action:"admin.created",entity_type:"admin",entity_id:uid,metadata:{role_key:roleKey}});const password_setup_email_sent=await sendPasswordSetup(email);return json({id:uid,email,role_key:roleKey,password_setup_email_sent},201,ch)}
if(action==="update_admin"){if(!await requireSuperAdmin())return json({error:"Forbidden"},403,ch);const targetId=String(body.admin_id||"");if(!targetId||targetId===actor.id)return json({error:"Akun Super Admin sendiri tidak dapat diubah melalui operasi ini."},400,ch);const {data:target}=await admin.from("admins").select("id,is_active,role_id,roles!inner(key),user_accounts!inner(status,full_name,phone)").eq("id",targetId).maybeSingle();if(!target)return json({error:"Admin tidak ditemukan."},404,ch);if((target as any).roles?.key==="super_admin")return json({error:"Akun Super Admin tidak dapat diubah melalui operasi ini."},403,ch);const roleKey=String(body.role_key||"");if(!allowedAdminRoles.has(roleKey))return json({error:"Role admin tidak valid."},400,ch);const {data:role}=await admin.from("roles").select("id,key").eq("key",roleKey).maybeSingle();if(!role)return json({error:"Role tidak ditemukan."},400,ch);const isActive=body.is_active!==false;const fullName=String(body.full_name??(target as any).user_accounts?.full_name??"").trim();if(!fullName)return json({error:"Nama admin wajib diisi."},400,ch);const phone=body.phone===undefined?(target as any).user_accounts?.phone:(body.phone||null);const title=body.title===undefined?undefined:(body.title||null);const employeeRef=body.employee_ref===undefined?undefined:(body.employee_ref||null);const accountPatch:any={full_name:fullName,phone,status:isActive?"active":"disabled"};const adminPatch:any={role_id:role.id,is_active:isActive};if(title!==undefined)adminPatch.title=title;if(employeeRef!==undefined)adminPatch.employee_ref=employeeRef;const {error:accountError}=await admin.from("user_accounts").update(accountPatch).eq("id",targetId).eq("account_type","admin");if(accountError)return json({error:"Gagal memperbarui akun admin."},400,ch);const {error:adminError}=await admin.from("admins").update(adminPatch).eq("id",targetId);if(adminError)return json({error:"Gagal memperbarui role/status admin."},400,ch);const {error:authError}=await admin.auth.admin.updateUserById(targetId,{ban_duration:isActive?"none":"876000h",user_metadata:{full_name:fullName}});if(authError)return json({error:"Data admin diperbarui tetapi status Auth gagal disinkronkan. Hubungi Super Admin."},500,ch);await admin.from("audit_logs").insert({actor_id:actor.id,action:"admin.updated",entity_type:"admin",entity_id:targetId,metadata:{role_key:roleKey,is_active:isActive}});return json({id:targetId,role_key:roleKey,is_active:isActive},200,ch)}
if(action==="create_investor"){const {data:allowed}=await caller.schema("app").rpc("has_permission",{p_key:"investors.create"});if(!allowed)return json({error:"Forbidden"},403,ch);const email=String(body.email||"").trim().toLowerCase(),legalName=String(body.legal_name||"").trim();if(!email||!legalName)return json({error:"Nama legal dan email wajib diisi."},400,ch);const {data:created,error:authError}=await admin.auth.admin.createUser({email,email_confirm:true,user_metadata:{full_name:legalName,must_set_password:true}});if(authError||!created.user)return json({error:"Gagal membuat akun investor."},400,ch);const uid=created.user.id,ref="INV-"+crypto.randomUUID().replaceAll("-","").slice(0,10).toUpperCase();const {error:accountError}=await admin.from("user_accounts").insert({id:uid,account_type:"investor",status:"disabled",email,full_name:legalName,phone:body.whatsapp_number||null,locale:"id",timezone:"Asia/Makassar"});if(accountError){await admin.auth.admin.deleteUser(uid);return json({error:"Gagal membuat akun investor."},400,ch)}const {error:investorError}=await admin.from("investors").insert({id:uid,reference_code:ref,status:"submitted",investor_type:body.investor_type==="institution"?"institution":"individual",legal_name:legalName,country:body.country||"ID",city:body.city||null,address:body.address||null,organization_name:body.organization_name||null,organization_role:body.organization_role||null,application_note:body.application_note||null,whatsapp_number:body.whatsapp_number||null,applied_at:new Date().toISOString(),relationship_manager_id:actor.id});if(investorError){await admin.from("user_accounts").delete().eq("id",uid);await admin.auth.admin.deleteUser(uid);return json({error:"Gagal membuat investor."},400,ch)}await admin.from("audit_logs").insert({actor_id:actor.id,action:"investor.created",entity_type:"investor",entity_id:uid,metadata:{reference_code:ref,status:"submitted"}});const password_setup_email_sent=await sendPasswordSetup(email);return json({id:uid,reference_code:ref,status:"submitted",password_setup_email_sent},201,ch)}
return json({error:"Unknown action"},400,ch)});
function json(value:unknown,status=200,corsHeaders:Record<string,string>={}){return new Response(JSON.stringify(value),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}})}
