create table if not exists public.finance_adjustments(
 id uuid primary key default gen_random_uuid(),adjustment_no text not null unique,financial_period_id uuid not null references public.financial_periods(id),source_entity_type text not null check(source_entity_type in('finance_expense','finance_payment','finance_refund','financial_report')),source_entity_id uuid not null,adjustment_kind text not null check(adjustment_kind in('correction','reversal')),cost_class public.finance_cost_class,amount_delta numeric(20,2) not null check(amount_delta<>0),reason text not null check(length(btrim(reason))>=10),evidence_asset_id uuid references public.media_assets(id),status text not null default 'posted' check(status='posted'),posted_on date not null,created_by uuid not null default auth.uid(),created_at timestamptz not null default now(),idempotency_key text not null unique check(length(btrim(idempotency_key))>=8),constraint finance_adjustment_reversal_negative check(adjustment_kind<>'reversal' or amount_delta<0));
alter table public.finance_adjustments enable row level security;
revoke all on table public.finance_adjustments from public,anon,authenticated;grant select on table public.finance_adjustments to authenticated;
create policy finance_adjustments_admin_read on public.finance_adjustments for select to authenticated using(app.has_permission('financial_reports.view') or app.has_permission('finance_expenses.record'));
create or replace function app.guard_finance_adjustment_immutable() returns trigger language plpgsql security definer set search_path='' as $$ begin raise exception 'Posted finance adjustments are immutable.' using errcode='42501';end $$;
revoke all on function app.guard_finance_adjustment_immutable() from public,anon,authenticated;grant execute on function app.guard_finance_adjustment_immutable() to service_role;
create trigger trg_finance_adjustment_immutable before update or delete on public.finance_adjustments for each row execute function app.guard_finance_adjustment_immutable();
create or replace function app.post_finance_adjustment(p_financial_period_id uuid,p_source_entity_type text,p_source_entity_id uuid,p_adjustment_kind text,p_cost_class public.finance_cost_class,p_amount_delta numeric,p_reason text,p_evidence_asset_id uuid,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare fp public.financial_periods%rowtype;v_id uuid;v_existing public.finance_adjustments%rowtype;v_source_date date;v_source_period uuid;
begin
 if not app.has_permission('finance_expenses.record') then raise exception 'Missing permission: finance_expenses.record' using errcode='42501';end if;
 if p_adjustment_kind not in('correction','reversal') or p_amount_delta is null or p_amount_delta=0 or(p_adjustment_kind='reversal' and p_amount_delta>=0) then raise exception 'Invalid adjustment amount/kind.' using errcode='23514';end if;
 if length(btrim(coalesce(p_reason,'')))<10 or length(btrim(coalesce(p_idempotency_key,'')))<8 then raise exception 'Reason and idempotency key are required.' using errcode='23514';end if;
 select * into fp from public.financial_periods where id=p_financial_period_id for share;if fp.id is null then raise exception 'Posting period not found.' using errcode='P0002';end if;perform app.assert_canonical_financial_period(fp.id);
 if fp.status<>'open' then raise exception 'Adjustment must be posted to an open canonical period.' using errcode='42501';end if;
 if app.accounting_date(now()) not between fp.starts_on and fp.ends_on then raise exception 'Adjustment posting period must contain the current accounting date.' using errcode='23514';end if;
 select * into v_existing from public.finance_adjustments where idempotency_key=p_idempotency_key;if found then if v_existing.financial_period_id=p_financial_period_id and v_existing.source_entity_type=p_source_entity_type and v_existing.source_entity_id=p_source_entity_id and v_existing.amount_delta=p_amount_delta then return v_existing.id;end if;raise exception 'Idempotency key already used with different adjustment data.' using errcode='23505';end if;
 case p_source_entity_type when 'finance_expense' then select expense_on into v_source_date from public.finance_expenses where id=p_source_entity_id;when 'finance_payment' then select app.accounting_date(received_at) into v_source_date from public.finance_payments where id=p_source_entity_id;when 'finance_refund' then select app.accounting_date(processed_at) into v_source_date from public.finance_refunds where id=p_source_entity_id;when 'financial_report' then select fp2.ends_on into v_source_date from public.financial_reports fr join public.financial_periods fp2 on fp2.id=fr.financial_period_id where fr.id=p_source_entity_id;else raise exception 'Unsupported adjustment source.' using errcode='23514';end case;
 if v_source_date is null then raise exception 'Adjustment source not found or has no accounting date.' using errcode='23503';end if;
 select id into v_source_period from public.financial_periods where app.is_canonical_financial_period(id) and v_source_date between starts_on and ends_on and status in('closed','locked') order by case status when 'locked' then 0 else 1 end,period_type limit 1;
 if v_source_period is null then raise exception 'Source must belong to a closed or locked canonical period.' using errcode='23514';end if;
 if p_evidence_asset_id is not null and not exists(select 1 from public.media_assets where id=p_evidence_asset_id and finalized_at is not null) then raise exception 'Adjustment evidence must be finalized.' using errcode='23503';end if;
 insert into public.finance_adjustments(adjustment_no,financial_period_id,source_entity_type,source_entity_id,adjustment_kind,cost_class,amount_delta,reason,evidence_asset_id,posted_on,created_by,idempotency_key) values('ADJ-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),fp.id,p_source_entity_type,p_source_entity_id,p_adjustment_kind,p_cost_class,p_amount_delta,btrim(p_reason),p_evidence_asset_id,app.accounting_date(now()),auth.uid(),p_idempotency_key) returning id into v_id;
 insert into public.audit_logs(actor_user_id,actor_type,action,entity_type,entity_id,summary,changes) values(auth.uid(),app.current_actor_type(),'finance.adjustment_posted','finance_adjustment',v_id,'Financial adjustment posted to open period.',jsonb_build_object('posting_period_id',fp.id,'source_period_id',v_source_period,'source_entity_type',p_source_entity_type,'source_entity_id',p_source_entity_id,'adjustment_kind',p_adjustment_kind,'cost_class',p_cost_class,'amount_delta',p_amount_delta,'reason',btrim(p_reason)));return v_id;
end $$;
revoke all on function app.post_finance_adjustment(uuid,text,uuid,text,public.finance_cost_class,numeric,text,uuid,text) from public,anon;grant execute on function app.post_finance_adjustment(uuid,text,uuid,text,public.finance_cost_class,numeric,text,uuid,text) to authenticated,service_role;