-- Dashboard-safe readiness projection for canonical period closing.
create or replace function app.financial_period_close_readiness(p_period_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare fp public.financial_periods%rowtype;v_pending bigint;v_unresolved bigint;v_confirmed bigint;v_matched bigint;v_unmatched bigint;v_pay numeric(20,2);v_ref numeric(20,2);v_exp numeric(20,2);v_report public.financial_reports%rowtype;v_rep_rev numeric(20,2):=0;v_rep_exp numeric(20,2):=0;v_report_reconciled boolean:=false;v_period_ended boolean;
begin
 if not app.has_permission('financial_reports.view') and not app.has_permission('financial_periods.close') then raise exception 'Missing financial period readiness permission.' using errcode='42501';end if;
 select * into fp from public.financial_periods where id=p_period_id;if fp.id is null then raise exception 'Financial period not found.' using errcode='P0002';end if;perform app.assert_canonical_financial_period(fp.id);v_period_ended:=fp.ends_on<app.accounting_date(now());
 select count(*) into v_pending from public.finance_payments p where p.status='pending' and p.received_at is not null and app.accounting_date(p.received_at) between fp.starts_on and fp.ends_on;
 select count(*) into v_unresolved from public.finance_refunds r join public.finance_payments p on p.id=r.payment_id where r.status in('requested','approved') and p.received_at is not null and app.accounting_date(p.received_at) between fp.starts_on and fp.ends_on;
 select count(*),coalesce(sum(p.amount),0) into v_confirmed,v_pay from public.finance_payments p where p.status='confirmed' and p.received_at is not null and app.accounting_date(p.received_at) between fp.starts_on and fp.ends_on;
 select count(*) into v_matched from public.finance_payments p where p.status='confirmed' and p.received_at is not null and app.accounting_date(p.received_at) between fp.starts_on and fp.ends_on and exists(select 1 from public.finance_bank_reconciliations br where br.payment_id=p.id and br.status='matched' and br.invoice_id is not distinct from p.invoice_id and br.bank_amount is not distinct from p.amount);
 v_unmatched:=greatest(v_confirmed-v_matched,0);
 select coalesce(sum(r.amount),0) into v_ref from public.finance_refunds r where r.status='processed' and r.processed_at is not null and app.accounting_date(r.processed_at) between fp.starts_on and fp.ends_on;
 select coalesce(sum(e.total_amount),0) into v_exp from public.finance_expenses e where e.status='recorded' and e.expense_on between fp.starts_on and fp.ends_on;
 select * into v_report from public.financial_reports fr where fr.financial_period_id=fp.id and fr.status='approved' order by fr.updated_at desc limit 1;
 if v_report.id is not null and v_report.current_version_id is not null then select coalesce(max(amount) filter(where line_key='revenue_total'),0),coalesce(max(amount) filter(where line_key='expense_total'),0) into v_rep_rev,v_rep_exp from public.financial_line_items where financial_report_version_id=v_report.current_version_id;v_report_reconciled:=v_rep_rev is not distinct from greatest(v_pay-v_ref,0) and v_rep_exp is not distinct from v_exp;end if;
 return jsonb_build_object('period_id',fp.id,'status',fp.status,'period_ended',v_period_ended,'pending_payments',v_pending,'unresolved_refunds',v_unresolved,'confirmed_payments',v_confirmed,'matched_reconciliations',v_matched,'unmatched_confirmed_payments',v_unmatched,'confirmed_payment_amount',v_pay,'processed_refund_amount',v_ref,'net_receipts',greatest(v_pay-v_ref,0),'recorded_expenses',v_exp,'approved_report_id',v_report.id,'approved_report_present',v_report.id is not null,'reported_revenue',v_rep_rev,'reported_expenses',v_rep_exp,'report_reconciled',v_report_reconciled,'ready_to_close',fp.status='open' and v_period_ended and v_pending=0 and v_unresolved=0 and v_unmatched=0 and v_report.id is not null and v_report_reconciled,'ready_to_lock',fp.status='closed' and v_report.id is not null);
end $$;
revoke all on function app.financial_period_close_readiness(uuid) from public,anon;
grant execute on function app.financial_period_close_readiness(uuid) to authenticated,service_role;