-- Canonical accounting totals include signed post-close adjustments.
create or replace function app.financial_period_accounting_totals(p_period_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare fp public.financial_periods%rowtype;v_pay numeric:=0;v_ref numeric:=0;v_base_exp numeric:=0;v_rev_adj numeric:=0;v_exp_adj numeric:=0;v_hpp numeric:=0;v_agent numeric:=0;v_partner numeric:=0;v_marketing numeric:=0;v_payment numeric:=0;v_opex numeric:=0;v_tax numeric:=0;v_other numeric:=0;v_embedded_tax numeric:=0;v_rev numeric:=0;v_exp numeric:=0;
begin
 select * into fp from public.financial_periods where id=p_period_id;if fp.id is null then raise exception 'Financial period not found.' using errcode='P0002';end if;perform app.assert_canonical_financial_period(fp.id);
 select coalesce(sum(amount),0) into v_pay from public.finance_payments where status='confirmed' and received_at is not null and app.accounting_date(received_at) between fp.starts_on and fp.ends_on;
 select coalesce(sum(amount),0) into v_ref from public.finance_refunds where status='processed' and processed_at is not null and app.accounting_date(processed_at) between fp.starts_on and fp.ends_on;
 select coalesce(sum(total_amount),0),coalesce(sum(total_amount)filter(where cost_class='direct_cost'),0),coalesce(sum(total_amount)filter(where cost_class='agent_fee'),0),coalesce(sum(total_amount)filter(where cost_class='partner_fee'),0),coalesce(sum(total_amount)filter(where cost_class='marketing_fee'),0),coalesce(sum(total_amount)filter(where cost_class='payment_fee'),0),coalesce(sum(total_amount)filter(where cost_class='operating_expense'),0),coalesce(sum(total_amount)filter(where cost_class='tax'),0),coalesce(sum(total_amount)filter(where cost_class='other'),0),coalesce(sum(tax_amount),0) into v_base_exp,v_hpp,v_agent,v_partner,v_marketing,v_payment,v_opex,v_tax,v_other,v_embedded_tax from public.finance_expenses where status='recorded' and expense_on between fp.starts_on and fp.ends_on;
 select coalesce(sum(amount_delta)filter(where account_side='revenue'),0),coalesce(sum(amount_delta)filter(where account_side='expense'),0) into v_rev_adj,v_exp_adj from public.finance_adjustments where status='posted' and financial_period_id=fp.id;
 select v_hpp+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='direct_cost'),0),v_agent+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='agent_fee'),0),v_partner+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='partner_fee'),0),v_marketing+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='marketing_fee'),0),v_payment+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='payment_fee'),0),v_opex+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='operating_expense'),0),v_tax+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='tax'),0),v_other+coalesce(sum(amount_delta)filter(where account_side='expense' and cost_class='other'),0) into v_hpp,v_agent,v_partner,v_marketing,v_payment,v_opex,v_tax,v_other from public.finance_adjustments where status='posted' and financial_period_id=fp.id;
 v_rev:=greatest(v_pay-v_ref,0)+v_rev_adj;v_exp:=v_base_exp+v_exp_adj;
 return jsonb_build_object('confirmed_payments',v_pay,'processed_refunds',v_ref,'base_net_receipts',greatest(v_pay-v_ref,0),'revenue_adjustments',v_rev_adj,'net_revenue',v_rev,'base_expenses',v_base_exp,'expense_adjustments',v_exp_adj,'expense_total',v_exp,'hpp',v_hpp,'agent_fee',v_agent,'partner_fee',v_partner,'marketing_fee',v_marketing,'payment_fee',v_payment,'operating_expense',v_opex,'tax_expense',v_tax,'other_expense',v_other,'embedded_tax_amount',v_embedded_tax);
end $$;
revoke all on function app.financial_period_accounting_totals(uuid) from public,anon,authenticated;grant execute on function app.financial_period_accounting_totals(uuid) to service_role;

create or replace function app.financial_report_profit_loss_breakdown(p_report_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare r public.financial_reports%rowtype;fp public.financial_periods%rowtype;t jsonb;v_rev numeric;v_exp numeric;v_hpp numeric;
begin if not(app.has_permission('financial_reports.view')or app.has_permission('financial_reports.update'))then raise exception 'Missing financial report permission.' using errcode='42501';end if;select * into r from public.financial_reports where id=p_report_id;if r.id is null then raise exception 'Financial report not found.' using errcode='P0002';end if;select * into fp from public.financial_periods where id=r.financial_period_id;perform app.assert_canonical_financial_period(fp.id);t:=app.financial_period_accounting_totals(fp.id);v_rev=(t->>'net_revenue')::numeric;v_exp=(t->>'expense_total')::numeric;v_hpp=(t->>'hpp')::numeric;return t||jsonb_build_object('period_start',fp.starts_on,'period_end',fp.ends_on,'gross_profit',v_rev-v_hpp,'net_profit',v_rev-v_exp,'gross_margin_percent',case when v_rev<>0 then round(((v_rev-v_hpp)/v_rev)*100,2)else 0 end,'net_margin_percent',case when v_rev<>0 then round(((v_rev-v_exp)/v_rev)*100,2)else 0 end);end $$;

create or replace function app.financial_report_cash_reconciliation(p_report_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.financial_reports%rowtype;fp public.financial_periods%rowtype;t jsonb;v_rep_rev numeric;v_rep_exp numeric;
begin if not(app.has_permission('financial_reports.view')or app.has_permission('financial_reports.update'))then raise exception 'Missing financial report permission.' using errcode='42501';end if;select * into r from public.financial_reports where id=p_report_id;if r.id is null or r.current_version_id is null then raise exception 'Financial report not found.' using errcode='P0002';end if;select * into fp from public.financial_periods where id=r.financial_period_id;perform app.assert_canonical_financial_period(fp.id);t:=app.financial_period_accounting_totals(fp.id);select coalesce(max(amount)filter(where line_key='revenue_total'),0),coalesce(max(amount)filter(where line_key='expense_total'),0)into v_rep_rev,v_rep_exp from public.financial_line_items where financial_report_version_id=r.current_version_id;return t||jsonb_build_object('period_start',fp.starts_on,'period_end',fp.ends_on,'accounting_timezone',app.accounting_timezone(),'net_receipts',(t->>'net_revenue')::numeric,'recorded_expenses',(t->>'expense_total')::numeric,'reported_revenue',v_rep_rev,'reported_expenses',v_rep_exp,'revenue_matches',v_rep_rev=(t->>'net_revenue')::numeric,'expenses_match',v_rep_exp=(t->>'expense_total')::numeric,'reconciled',v_rep_rev=(t->>'net_revenue')::numeric and v_rep_exp=(t->>'expense_total')::numeric);end $$;

-- Close readiness and close-period use the same canonical helper so a report that omits
-- a posted adjustment cannot reconcile or close. Their production definitions are replaced
-- in the following migration to keep this file reviewable.