-- Preserve finance authorization while avoiding overlapping permissive SELECT policies.
drop policy if exists finance_expenses_manage on public.finance_expenses;
drop policy if exists finance_expenses_read on public.finance_expenses;
create policy finance_expenses_select on public.finance_expenses for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_expenses_insert on public.finance_expenses for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_expenses_update on public.finance_expenses for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_expenses_delete on public.finance_expenses for delete to authenticated using (app.has_permission('financial_reports.update'));
drop policy if exists finance_invoice_items_manage on public.finance_invoice_items;
drop policy if exists finance_invoice_items_read on public.finance_invoice_items;
create policy finance_invoice_items_select on public.finance_invoice_items for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_invoice_items_insert on public.finance_invoice_items for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_invoice_items_update on public.finance_invoice_items for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_invoice_items_delete on public.finance_invoice_items for delete to authenticated using (app.has_permission('financial_reports.update'));
drop policy if exists finance_invoices_manage on public.finance_invoices;
drop policy if exists finance_invoices_read on public.finance_invoices;
create policy finance_invoices_select on public.finance_invoices for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_invoices_insert on public.finance_invoices for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_invoices_update on public.finance_invoices for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_invoices_delete on public.finance_invoices for delete to authenticated using (app.has_permission('financial_reports.update'));
drop policy if exists finance_payments_manage on public.finance_payments;
drop policy if exists finance_payments_read on public.finance_payments;
create policy finance_payments_select on public.finance_payments for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_payments_insert on public.finance_payments for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_payments_update on public.finance_payments for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_payments_delete on public.finance_payments for delete to authenticated using (app.has_permission('financial_reports.update'));
drop policy if exists finance_products_manage on public.finance_products;
drop policy if exists finance_products_read on public.finance_products;
create policy finance_products_select on public.finance_products for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_products_insert on public.finance_products for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_products_update on public.finance_products for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_products_delete on public.finance_products for delete to authenticated using (app.has_permission('financial_reports.update'));
drop policy if exists finance_refunds_manage on public.finance_refunds;
drop policy if exists finance_refunds_read on public.finance_refunds;
create policy finance_refunds_select on public.finance_refunds for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_refunds_insert on public.finance_refunds for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_refunds_update on public.finance_refunds for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_refunds_delete on public.finance_refunds for delete to authenticated using (app.has_permission('financial_reports.update'));
drop policy if exists finance_settings_manage on public.finance_settings;
drop policy if exists finance_settings_read on public.finance_settings;
create policy finance_settings_select on public.finance_settings for select to authenticated using (app.has_permission('financial_reports.view') or app.has_permission('financial_reports.update'));
create policy finance_settings_insert on public.finance_settings for insert to authenticated with check (app.has_permission('financial_reports.update'));
create policy finance_settings_update on public.finance_settings for update to authenticated using (app.has_permission('financial_reports.update')) with check (app.has_permission('financial_reports.update'));
create policy finance_settings_delete on public.finance_settings for delete to authenticated using (app.has_permission('financial_reports.update'));
