-- Harden finance/payout proof registration: metadata may only be registered
-- after the caller has actually uploaded the object, and size/MIME must agree
-- with Storage metadata. Keeps the existing RPC signatures/defaults.

create or replace function app.register_finance_expense_receipt(p_path text,p_original_filename text,p_mime_type text,p_byte_size bigint) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_uid uuid:=auth.uid();v_obj storage.objects%rowtype;v_size bigint;v_mime text;begin
if v_uid is null or not app.has_permission('finance_expenses.record') then raise exception 'Missing permission: finance_expenses.record' using errcode='42501';end if;
if p_path not like 'finance/expenses/%' then raise exception 'Invalid finance expense receipt path.' using errcode='23514';end if;
if lower(coalesce(p_mime_type,'')) not in('application/pdf','image/jpeg','image/png','image/webp') then raise exception 'Expense receipt must be PDF, JPEG, PNG, or WEBP.' using errcode='23514';end if;
if p_byte_size<=0 or p_byte_size>10485760 then raise exception 'Expense receipt must be 1 byte to 10 MB.' using errcode='23514';end if;
select * into v_obj from storage.objects where bucket_id='company-documents' and name=p_path and owner_id=v_uid::text;if not found then raise exception 'Uploaded expense receipt object was not found.' using errcode='P0002';end if;
v_size:=nullif(v_obj.metadata->>'size','')::bigint;v_mime:=lower(coalesce(v_obj.metadata->>'mimetype',''));if v_size is not null and v_size<>p_byte_size then raise exception 'Uploaded object size does not match registration.' using errcode='23514';end if;if v_mime<>'' and v_mime<>lower(p_mime_type) then raise exception 'Uploaded object MIME type does not match registration.' using errcode='23514';end if;
insert into public.media_assets(bucket,path,original_filename,mime_type,byte_size,visibility,uploaded_by,finalized_at) values('company-documents',p_path,btrim(p_original_filename),lower(p_mime_type),coalesce(v_size,p_byte_size),'restricted',v_uid,now()) returning id into v_id;return v_id;end $$;

create or replace function app.register_finance_refund_proof_asset(p_path text,p_original_filename text,p_mime_type text,p_byte_size bigint) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_uid uuid:=auth.uid();v_obj storage.objects%rowtype;v_size bigint;v_mime text;begin
if v_uid is null or not app.has_permission('finance_refunds.process') then raise exception 'Tidak memiliki izin bukti refund.' using errcode='42501';end if;if p_path not like 'finance/refunds/%' then raise exception 'Path bukti refund tidak valid.' using errcode='22023';end if;
if lower(coalesce(p_mime_type,'')) not in('application/pdf','image/jpeg','image/png','image/webp') then raise exception 'Bukti refund harus PDF/JPG/PNG/WEBP.' using errcode='22023';end if;if p_byte_size is null or p_byte_size<=0 or p_byte_size>10485760 then raise exception 'Ukuran bukti refund tidak valid.' using errcode='22023';end if;
select * into v_obj from storage.objects where bucket_id='company-documents' and name=p_path and owner_id=v_uid::text;if not found then raise exception 'File bukti refund tidak ditemukan atau bukan milik pengunggah.' using errcode='P0002';end if;
v_size:=nullif(v_obj.metadata->>'size','')::bigint;v_mime:=lower(coalesce(v_obj.metadata->>'mimetype',''));if v_size is not null and v_size<>p_byte_size then raise exception 'Ukuran object tidak cocok.' using errcode='23514';end if;if v_mime<>'' and v_mime<>lower(p_mime_type) then raise exception 'MIME object tidak cocok.' using errcode='23514';end if;
insert into public.media_assets(bucket,path,original_filename,mime_type,byte_size,visibility,uploaded_by,finalized_at) values('company-documents',p_path,btrim(p_original_filename),lower(p_mime_type),coalesce(v_size,p_byte_size),'restricted',v_uid,now()) returning id into v_id;return v_id;end $$;

create or replace function app.register_profit_distribution_payment_proof(p_allocation_id uuid,p_storage_path text,p_original_file_name text,p_mime_type text,p_file_size_bytes bigint,p_payment_reference text default null::text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_allocation public.profit_distribution_allocations%rowtype;v_id uuid;v_expected_prefix text;v_uid uuid:=auth.uid();v_obj storage.objects%rowtype;v_size bigint;v_mime text;begin
if v_uid is null or not app.has_permission('profit_distribution_payments.upload_proof') then raise exception 'Missing permission: profit_distribution_payments.upload_proof' using errcode='42501';end if;select * into v_allocation from public.profit_distribution_allocations where id=p_allocation_id for update;if v_allocation.id is null then raise exception 'Allocation not found.' using errcode='P0002';end if;if v_allocation.status<>'payable' then raise exception 'Payment proof can only be registered for a payable allocation.' using errcode='23514';end if;
v_expected_prefix:=v_allocation.investor_id::text||'/'||v_allocation.id::text||'/';if p_storage_path is null or position(v_expected_prefix in p_storage_path)<>1 then raise exception 'Invalid payment proof storage path.' using errcode='23514';end if;if length(btrim(coalesce(p_original_file_name,'')))=0 then raise exception 'Original file name is required.' using errcode='23514';end if;if lower(coalesce(p_mime_type,'')) not in('application/pdf','image/jpeg','image/png','image/webp') then raise exception 'Unsupported payment proof file type.' using errcode='23514';end if;if p_file_size_bytes is null or p_file_size_bytes<=0 or p_file_size_bytes>10485760 then raise exception 'Payment proof file size is invalid.' using errcode='23514';end if;
select * into v_obj from storage.objects where bucket_id='profit-distribution-proofs' and name=btrim(p_storage_path) and owner_id=v_uid::text;if not found then raise exception 'Uploaded payment proof object was not found or is not owned by uploader.' using errcode='P0002';end if;v_size:=nullif(v_obj.metadata->>'size','')::bigint;v_mime:=lower(coalesce(v_obj.metadata->>'mimetype',''));if v_size is not null and v_size<>p_file_size_bytes then raise exception 'Uploaded object size does not match registration.' using errcode='23514';end if;if v_mime<>'' and v_mime<>lower(p_mime_type) then raise exception 'Uploaded object MIME type does not match registration.' using errcode='23514';end if;
insert into public.profit_distribution_payment_proofs(allocation_id,investor_id,storage_bucket,storage_path,original_file_name,mime_type,file_size_bytes,payment_reference,uploaded_by) values(v_allocation.id,v_allocation.investor_id,'profit-distribution-proofs',btrim(p_storage_path),btrim(p_original_file_name),lower(p_mime_type),coalesce(v_size,p_file_size_bytes),nullif(btrim(coalesce(p_payment_reference,'')),''),v_uid) returning id into v_id;return v_id;end $$;
