import React,{useEffect,useState} from 'react';
import {FileText,LogOut,ReceiptText,WalletCards,Building2,TrendingUp} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import {downloadInvestorDocument,getInvestorDashboardData,type InvestorDistribution,type InvestorDocument,type InvestorPortfolio,type InvestorTransaction,type InvestorHolding,type InvestorInheritance,type SalesSummary} from '../../services/investorPortal';

const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
export const InvestorDashboard:React.FC<{onBack:()=>void;onLogout:()=>void}>=({onBack,onLogout})=>{
 const [profile,setProfile]=useState<InvestorPortfolio|null>(null),[holdings,setHoldings]=useState<InvestorHolding[]>([]),[inheritance,setInheritance]=useState<InvestorInheritance[]>([]),[transactions,setTransactions]=useState<InvestorTransaction[]>([]),[distributions,setDistributions]=useState<InvestorDistribution[]>([]),[documents,setDocuments]=useState<InvestorDocument[]>([]),[error,setError]=useState(''),[sales,setSales]=useState<SalesSummary|null>(null);
 useEffect(()=>{let active=true;const load=()=>void getInvestorDashboardData().then(d=>{if(!active)return;setProfile(d.profile);setHoldings(d.holdings);setInheritance(d.inheritance);setTransactions(d.transactions);setDistributions(d.distributions);setDocuments(d.documents);setSales(d.salesSummary);setError('')}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Gagal memuat data investor.')});load();const ch=supabase?.channel('investor-equity-live').on('postgres_changes',{event:'*',schema:'public',table:'ownership_holdings'},load).on('postgres_changes',{event:'*',schema:'public',table:'profit_distribution_allocations'},load).on('postgres_changes',{event:'*',schema:'public',table:'profit_distributions'},load).on('postgres_changes',{event:'*',schema:'public',table:'profit_distribution_payment_proofs'},load).on('postgres_changes',{event:'*',schema:'public',table:'ownership_transfers'},load).on('postgres_changes',{event:'*',schema:'public',table:'ownership_inheritance'},load).subscribe();return()=>{active=false;if(ch&&supabase)void supabase.removeChannel(ch)}},[]);
 const paid=distributions.filter(x=>x.status==='paid').reduce((a,b)=>a+Number(b.amount),0);
 return <div className="min-h-screen bg-[#f5f5f3] text-[#111]">
  <header className="bg-[#131314] text-white px-5 py-4"><div className="max-w-6xl mx-auto flex items-center justify-between gap-4"><div><div className="font-bold">Nuzultrip Equity</div><div className="text-xs text-white/50">{profile?profile.full_name+' · Investor':'Dashboard Investor'}</div></div><button onClick={onLogout} className="flex items-center gap-2 text-sm text-white/70"><LogOut size={16}/>Keluar</button></div></header>
  <main className="max-w-6xl mx-auto p-5 lg:p-8 space-y-6">
   {error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 text-sm">{error}</div>}
   <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Card label="Kode Investor" value={profile?.investor_code||'—'}/><Card label="Unit Kepemilikan" value={profile?String(profile.units):'—'}/><Card label="Persentase Kepemilikan" value={profile?Number(profile.ownership_percent).toLocaleString('id-ID')+'%':'—'}/><Card label="Nilai Investasi" value={profile?money(Number(profile.invested_amount)):'—'}/></div>
   <section className="bg-[#131314] text-white rounded-2xl p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-white/55 text-xs uppercase tracking-[.14em]"><Building2 size={15}/>Portofolio Equity</div><h1 className="text-2xl sm:text-3xl font-bold mt-2">{profile?.full_name||'Investor Nuzultrip'}</h1><p className="text-sm text-white/55 mt-1">Ringkasan kepemilikan, kinerja usaha, distribusi hasil, transaksi, dan dokumen investor.</p></div><div className="text-left sm:text-right"><div className="text-xs text-white/45">Total distribusi dibayar</div><div className="text-xl font-bold mt-1">{money(paid)}</div></div></div></section>
   <section className="bg-white border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Building2 size={18}/><h2 className="font-bold">Detail Kepemilikan Equity</h2></div>{holdings.length?<Table head={['Penawaran','Unit','Porsi','Harga / Unit','Nilai','Tanggal Perolehan','Transfer Mulai','Status']}>{holdings.map(h=><tr className="border-t" key={h.id}><Td><div className="font-semibold">{h.offering_name}</div><div className="text-xs text-black/45">{h.offering_code}{h.acquisition_reference?' · '+h.acquisition_reference:''}</div></Td><Td>{h.units}</Td><Td>{h.ownership_percent.toLocaleString('id-ID')}%</Td><Td>{money(h.unit_price)}</Td><Td>{money(h.invested_amount)}</Td><Td>{new Date(h.acquisition_at).toLocaleDateString('id-ID')}</Td><Td>{new Date(h.transfer_eligible_at).toLocaleDateString('id-ID')}</Td><Td>{h.status}</Td></tr>)}</Table>:<p className="text-sm text-black/45">Belum ada holding equity aktif.</p>}</section>
   <section className="bg-white border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><FileText size={18}/><h2 className="font-bold">Pewarisan Equity</h2></div>{inheritance.length?<Table head={['Tanggal','Penerima Manfaat','Unit','Status','Keterangan']}>{inheritance.map(i=><tr className="border-t" key={i.id}><Td>{new Date(i.requested_at).toLocaleDateString('id-ID')}</Td><Td>{i.beneficiary_name}</Td><Td>{i.units}</Td><Td>{i.status}</Td><Td>{i.rejection_reason||'—'}</Td></tr>)}</Table>:<p className="text-sm text-black/45">Belum ada proses pewarisan equity.</p>}</section>
   <section className="bg-white border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><TrendingUp size={18}/><h2 className="font-bold">Kinerja Penjualan Perusahaan</h2></div><p className="text-xs text-black/45 mb-4">Ringkasan agregat seluruh penjualan paket. Data pribadi pelanggan tidak ditampilkan.</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Mini label="Total Penjualan" value={sales?money(sales.total_sales):'—'}/><Mini label="Pembayaran Diterima" value={sales?money(sales.payments_received):'—'}/><Mini label="Sisa Tagihan" value={sales?money(sales.outstanding):'—'}/><Mini label="Refund" value={sales?money(sales.refunds):'—'}/><Mini label="Kas Bersih" value={sales?money(sales.net_cash):'—'}/><Mini label="Invoice" value={sales?String(sales.invoice_count):'—'}/><Mini label="DP / Partial" value={sales?String(sales.dp_count):'—'}/><Mini label="Lunas" value={sales?String(sales.paid_count):'—'}/><Mini label="Refunded" value={sales?String(sales.refunded_count):'—'}/><Mini label="Dibatalkan" value={sales?String(sales.cancelled_count):'—'}/><Mini label="Total Pax" value={sales?String(sales.pax):'—'}/></div></section>
   <section className="bg-white border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><ReceiptText size={18}/><h2 className="font-bold">Transaksi Equity Saya</h2></div>{transactions.length?<Table head={['Tanggal','Referensi','Keterangan','Jumlah','Status']}>{transactions.map(r=><tr className="border-t" key={r.id}><Td>{r.transaction_date}</Td><Td>{r.reference_no}</Td><Td>{r.description}</Td><Td>{money(Number(r.amount))}</Td><Td>{r.status}</Td></tr>)}</Table>:<p className="text-sm text-black/45">Belum ada transaksi equity individual yang tersedia untuk akun ini.</p>}</section>
   <section className="bg-white border rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><WalletCards size={18}/><h2 className="font-bold">Distribusi Hasil</h2></div><span className="text-sm font-bold">{money(paid)}</span></div><Table head={['Periode','Jumlah','Status','Tanggal Bayar']}>{distributions.map(r=><tr className="border-t" key={r.id}><Td>{r.period}</Td><Td>{money(Number(r.amount))}</Td><Td>{r.status}</Td><Td>{r.paid_at?new Date(r.paid_at).toLocaleDateString('id-ID'):'—'}</Td></tr>)}</Table></section>
   <section className="bg-white border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><FileText size={18}/><h2 className="font-bold">Dokumen Investor</h2></div><div className="grid md:grid-cols-2 gap-3">{documents.map(d=><button type="button" key={d.id} onClick={()=>void downloadInvestorDocument(d.id).catch(e=>setError(e instanceof Error?e.message:'Gagal membuka dokumen.'))} className="text-left border rounded-xl p-4 hover:bg-black/[.02]"><div className="font-semibold text-sm">{d.title}</div><div className="text-xs text-black/45 mt-1">{d.category}</div></button>)}</div></section>
   <button onClick={onBack} className="text-sm font-semibold">← Kembali ke Portal</button>
  </main>
 </div>
};
const Card=({label,value}:{label:string;value:string})=><div className="bg-white border rounded-2xl p-5"><p className="text-xs text-black/45">{label}</p><p className="text-xl font-bold mt-2">{value}</p></div>;
const Table=({head,children}:{head:string[];children:React.ReactNode})=><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{head.map(h=><th key={h} className="text-left px-3 py-3 text-xs text-black/45">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
const Td=({children}:{children:React.ReactNode})=><td className="px-3 py-3">{children}</td>;

const Mini=({label,value}:{label:string;value:string})=><div className="border rounded-xl p-4"><p className="text-xs text-black/45">{label}</p><p className="font-bold mt-2">{value}</p></div>;
